### ISSUE TITLE
Restrict protocol to TLS 1.3?

### ISSUE THREAD

**Issue by jfmcbrayer** [cl-plus-ssl/cl-plus-ssl#107]
Hi. I have a project (a server), where I want to restrict the protocol version to TLS 1.3.

My current code looks like:
```lisp
  (with-global-context ((make-context :disabled-protocols
                                      (list +ssl-op-no-sslv2+ +ssl-op-no-sslv3+
                                            +ssl-op-no-tlsv1+ +ssl-op-no-tlsv1-1+
                                            +ssl-op-no-tlsv1-2+))
                        :auto-free-p (not background))
     (usocket:socket-server host port #'gemini-handler ()
                           :multi-threading t
                           :element-type '(unsigned-byte 8)
                           :in-new-thread background)))

```

But because :method isn't set on make-context, the :disabled-protocols is ignored, I believe. I can't figure out any way to set :method. Am I doing something wrong, or is this not possible? I would settle for restricting to TLS 1.2 or higher if that's possible but this isn't.

**Comment by avodonosov** [comment]
I would try wrapping call to `make-ssl-server-stream` into `with-global-context`. And not creating new context every time, but creating it once and storing in a variable.

```common-lisp
(with-global-context (*my-ssl-context*)
    (make-ssl-server-stream ...))
```

**Comment by jfmcbrayer** [comment]
That's good advice, and I've done so, but it doesn't help with my issue.

**Comment by avodonosov** [comment]
@jfmcbrayer , the `make-context` function has `:method` argument.

**Comment by jfmcbrayer** [comment]
Thank you. But in neither the documentation, nor the source, nor random experimentation in SLIME, have I been able to find how to get a suitable value to pass as the :method argument.

**Comment by avodonosov** [comment]
This should be one of the constants from the ffi.lisp

```common-lisp

(define-ssl-function-ex (:vanished "1.1.0") ("SSLv23_client_method" ssl-v23-client-method)
    ssl-method)
(define-ssl-function-ex (:vanished "1.1.0") ("SSLv23_server_method" ssl-v23-server-method)
    ssl-method)
(define-ssl-function-ex (:vanished "1.1.0") ("SSLv23_method" ssl-v23-method)
    ssl-method)
(define-ssl-function-ex (:vanished "1.1.0") ("SSLv3_client_method" ssl-v3-client-method)
    ssl-method)
(define-ssl-function-ex (:vanished "1.1.0") ("SSLv3_server_method" ssl-v3-server-method)
    ssl-method)
(define-ssl-function-ex (:vanished "1.1.0") ("SSLv3_method" ssl-v3-method)
    ssl-method)
(define-ssl-function ("TLSv1_client_method" ssl-TLSv1-client-method)
    ssl-method)
(define-ssl-function ("TLSv1_server_method" ssl-TLSv1-server-method)
    ssl-method)
(define-ssl-function ("TLSv1_method" ssl-TLSv1-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_1_client_method" ssl-TLSv1-1-client-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_1_server_method" ssl-TLSv1-1-server-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_1_method" ssl-TLSv1-1-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_2_client_method" ssl-TLSv1-2-client-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_2_server_method" ssl-TLSv1-2-server-method)
    ssl-method)
(define-ssl-function-ex (:since "1.0.2") ("TLSv1_2_method" ssl-TLSv1-2-method)
    ssl-method)
(define-ssl-function-ex (:since "1.1.0") ("TLS_method" tls-method)
    ssl-method)

```

**Comment by jfmcbrayer** [comment]
Somehow, I can't seem to refer these constants...

```lisp
(defparameter *my-context* (cl+ssl:make-context :method cl+ssl::ssl-tlsv1-2-method))
```
says `The variable CL+SSL::SSL-TLSV1-2-METHOD is unbound.`

I'm obviously doing something wrong, but I can't manage to figure out what.

**Comment by avodonosov** [comment]
@jfmcbrayer., sorry, I used wrond word "constants'. Actually, those a functions, pass a return value of such functions as the method.

(cl+ssl::tls-method)

**Comment by jfmcbrayer** [comment]
Ah! That does the trick. Thank you very much.

**Comment by jfmcbrayer** [comment]
So, this works (ie, produces a working ssl context):

```lisp
  (setq *my-tls-context* (make-context :method (cl+ssl::ssl-tlsv1-2-method)
                                             :disabled-protocols
                                             (list +ssl-op-no-sslv2+ +ssl-op-no-sslv3+
                                                   +ssl-op-no-tlsv1+ +ssl-op-no-tlsv1-1+)))
```
but I'm still able to connect to this server with `openssl s_client -crlf -tls1_1 localhost:1965`. It does reject SSL2 and SSL3 connections, but accepts TLSv1 and TLSv1.1, which it shouldn't.

**Comment by avodonosov** [comment]
Maybe the default context is still used by your server? OpenSSL docs say

> TLSv1_2_method(), TLSv1_2_server_method(), TLSv1_2_client_method()
A TLS/SSL connection established with these methods will only understand the TLSv1.2 protocol. A client will send out TLSv1.2 client hello messages and will also indicate that it only understand TLSv1.2. A server will only understand TLSv1.2 client hello messages.

https://www.openssl.org/docs/man1.0.2/man3/TLSv1_2_method.html

**Comment by avodonosov** [comment]
Can you show how the *my-tls-context* used to create server sockets?

**Comment by jfmcbrayer** [comment]
Actually, that was it. I had creating the usocket:socket-server wrapped with with-global-context, but the tls stream is actually created in the handler, where I didn't have it wrapped with with-global-context. Adding it fixed the problem. Thanks for all your patience.
