### ISSUE TITLE
[feature request] dump x.509 certificate

### ISSUE THREAD

**Issue by cage2** [cl-plus-ssl/cl-plus-ssl#109]
Hi!

I am writing a gemini (https://gemini.circumlunar.space/) client and i am struggling with the policy for trusted certificates called TOFU (trust on the first use): basically you accept the certificate the server gives you the first time and refuse to connect if it changed (like SSH, i believe). Problem is how can i compare two certificates using cl+ssl? How can  i get a dump (binary or text encoded) of the whole certificate?
I learnt that `PEM_write_X509` but i do not know if this is the right function and moreover it writes on a `FILE*` stream, please can you help me?

Thank you in advance!
Bye!
C.

**Comment by avodonosov** [comment]
I've never done that, so I can't offer much help. 

See how cl+ssl code retrieves server certificate using `ssl-get-peer-certificate`
https://github.com/cl-plus-ssl/cl-plus-ssl/blob/ff4634a2addedc033394e93a402523532e9b470a/src/streams.lisp#L332

This function returns a pointer to the X509 structure: https://www.openssl.org/docs/man1.0.2/man3/SSL_get_peer_certificate.html

I don't know how do you want to compare certificates? Maybe convert to DER encoding and then compute hashode? OpenSSL function i2d_X509 should be helpful to convert the internal OpenSSL C structure representation to DER: https://www.openssl.org/docs/man1.0.2/man3/d2i_X509.html
If you need DER encoding 

Maybe (I'm not sure) you can find some useful examples of how to work with the X509 structure in https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/x509.lisp and corresponding unit tests.

**Comment by cage2** [comment]
On Sat, Jun 20, 2020 at 06:26:15PM -0700, Anton Vodonosov wrote:

Hi Anton!

> I've never done that, so I can't offer much help.

No problem, even just an hint can provide a good help! :)

> See how cl+ssl code retrieves server certificate using `ssl-get-peer-certificate`
> https://github.com/cl-plus-ssl/cl-plus-ssl/blob/ff4634a2addedc033394e93a402523532e9b470a/src/streams.lisp#L332

Yes, i checked the source and, after, i was able to retrieve the certificate.

> This function returns a pointer to the X509 structure: https://www.openssl.org/docs/man1.0.2/man3/SSL_get_peer_certificate.html
>
> I don't know how do you want to compare certificates? Maybe convert to DER encoding and then compute hashode?

yes, that is my idea (and what i think other clients do)! :)

> OpenSSL function i2d_X509 should be helpful to convert the internal OpenSSL C structure representation to DER: https://www.openssl.org/docs/man1.0.2/man3/d2i_X509.html
> If you need DER encoding

Thank you Anton, i think this is the function i need! :)

Just another question,  given that my software is using  cl+ssl, can i
just write a simple CFFI wrapper in  my code for this function? I mean
ca i be sure CFFI will find  the C function given that libssl has been
loaded by cl+ssl?

Thank you very much!
C.

**Comment by cage2** [comment]
Hi!

I was able to hack something useful using the function you suggested. As far as i can understand this should be good enough to have TOFU!

Thank you again for your help! :)
Bye!
C.
