### ISSUE TITLE
Please add "lib/libssl.so.10" to Unix Foreign Library List In `reload.lisp'

### ISSUE THREAD

**Issue by spyrosoft** [cl-plus-ssl/cl-plus-ssl#12]
Or is there possibly a more general/automated technique for identifying which libssl.so to use?

**Comment by avodonosov** [comment]
Does it work for you if we just add "libssl.so.10"? (without "lib/')

As for general technique - I am not aware of any.

**Comment by spyrosoft** [comment]
Yes, "libssl.so.10" is correct, in the same fashion as the existing "libssl.so.4".

I looked into the issue a little further and it turns out that this is an issue for the Redhat family only: https://www.openssl.org/support/faq.html#BUILD8. Because the number appended to the end is a build number and not a version number, the pattern is incremental integers. (Yay?)

What do you think, is it worth it to include "libssl.so.4" all the way through something like "libssl.so.30" to make it future-proof for a while?

**Comment by avodonosov** [comment]
In principle we could do this, but in your link I don't see a confirmation that .10 is a build number. The link talk about build number, but it doesn't say that the build number is appended to an .so file name.

What is your RedHat version? If RedHat 7.1, then we probably should add libssl.so.0.9.6, and if 7.2 then libssl.so.0.9.6b.

Can you please check this variant? (These .so files should be located in /lib/, according to your link)

**Comment by spyrosoft** [comment]
I'm using Fedora 21 and CentOS 7.1.1503. The current file in both is "libssl.so.10". I know for sure that last time I updated with (ql:update-dist "quicklisp"), the file was "libssl.so.6". And presumably before it was "libssl.so.4".

That said, it's not such a big deal to hack reload.lisp every time I upgrade quicklisp. It doesn't come up very often, and it's very distro specific. I wonder if anyone else is having this issue at all.

**Comment by avodonosov** [comment]
I mean, they say that  libssl.so.N is a symlink to libssl.so.0.9.6b: 

"/lib/libssl.so.0.9.6b and /lib/libcrypto.so.0.9.6b with symlinks /lib/libssl.so.2 and /lib/libcrypto.so.2 respectively"

**Comment by spyrosoft** [comment]
Oh my goodness. It looks like it was a symlink all along. Sorry for spinning your wheels.

```
/usr/lib64/libssl3.so
/usr/lib64/libssl.so.10 -> libssl.so.1.0.1e
/usr/lib64/libssl.so.1.0.1e
```

And just now I updated production and everything worked fine. I notice that libssl.so.1.0.1e is in the list. I have no idea why it didn't work in dev. If it ever happens again I'll let you know.

**Comment by avodonosov** [comment]
No problem, I welcome suggestions like this. If something doesn't work, please let me know.

Sorry for being that meticulous, it's not because I don't want to commit the fix. I'am saying, I was ready to add those 30 names, I just like to understand what I am doing and to commit the best solution.

I guess previously the symlink was probably pointing to libcrypto.so.0.9.6b, which is absent in reaload.lisp. Now that you have updated, the symlink points to new .so file. It's just my guess, I don't know.

Anyway, thanks for taking time to report this and suggest a solution.

Any new information is welcome.
