### ISSUE TITLE
The symbol "HOST-TO-HOSTNAME" is not external in the USOCKET package.

### ISSUE THREAD

**Issue by WProffitt** [cl-plus-ssl/cl-plus-ssl#129]
I recently updated to Win64 OpenSSL v1.1.1k. I am using Lispworks 64 bit Enterprise edition, my Usocket is 0.6.3.2 and I am on Windows 10 pro 64 bit. 

I keep getting the following error when loading your library.

(ql:quickload 'cl+ssl)

To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
..................................................
[package cl+ssl]......................
Creating foreign funcallable for signature (:POINTER) -> :INT
Creating foreign funcallable for signature (:POINTER :POINTER :INT) -> :VOID
..

**++++ Error between functions:
  The symbol "HOST-TO-HOSTNAME" is not external in the USOCKET package.
; *** 1 error detected, no fasl file produced.

Any idea what is wrong?

**Comment by avodonosov** [comment]
Apparently the usocket does not provide a public symbol that that cl+ssl expects. 

Try a matching version of usocket.  For example the latest cl+ssl and the latest usocket.

Why don't you use the usocket version from Quicklisp?

**Comment by WProffitt** [comment]
Thanks for the reply.

Quicklisp delivers the following versions:

#<QL-DIST:SYSTEM cl+ssl / cl+ssl-20160208-git / quicklisp 2016-02-08>
#<QL-DIST:SYSTEM usocket / usocket-0.6.3.2 / quicklisp 2016-02-08>

The USOCKET version Quicklisp delivers is the one I am using, the version of CL+SSL from 2016 that quicklisp delivers does not make use of 64 bit OpenSSL libraries and instead tries to load the 32 bit library "LIBSSL". Unfortunately that does not work in 64 bit Lispworks.

**Comment by avodonosov** [comment]
To get updated software, use: `(ql:update-dist` "quicklisp")``

**Comment by avodonosov** [comment]
I hope that helps
