### ISSUE TITLE
CFFI issues on Allegro CL

### ISSUE THREAD

**Issue by rpgoldman** [cl-plus-ssl/cl-plus-ssl#13]
When I try to build CL+SSL on Allegro Mac OS X, I get a bunch of warnings like this:

```lisp
; While FILE-COMPILING #'"ffi.lisp" in
#P"/Users/rpg/stratus/stratus-trunk/code/externals/cl+ssl/ffi.lisp"
; starting at file character position 1480:
Warning: While defining |%cffi-foreign-function/SSL-LIBRARY-INIT|,
         :release-heap not implemented for this architecture; argument
         ignored. This warning is suppressed when
         :RELEASE-HEAP-IGNORABLE is specified as true in the
         def-foreign-call.
```

I get one of these for each of the FFIs, as far as I can tell, because all of the stubs specify `:release-heap :always`

Are these warnings important, or could we just muffle them and do without `:release-heap`?

Note I'm not entirely sure where in the chain of macros that release-heap gets inserted.

**Comment by avodonosov** [comment]
It's the first time I hear about `release-heap`, I don't know what it is. Seem like an Allegro's feature.

I googled and found it here: https://github.com/cffi/cffi/blob/53af3871ec74f20cf50539680ff2251d50f32911/src/cffi-allegro.lisp#L321

BTW, it's a recently introduced change: https://github.com/cffi/cffi/commit/53af3871ec74f20cf50539680ff2251d50f32911#diff-cc15fc1199bd48567cba333c199878b6

So, I guess `release-heap` is an Allegro's feature, which is not supported on Mac OS X.

Maybe @ffilozov or @luismbo can answer your question.

**Comment by avodonosov** [comment]
The relevant Allegro docs: http://franz.com/support/documentation/9.0/doc/operators/ff/def-foreign-call.htm

**Comment by avodonosov** [comment]
After brief reading of Allegro docs I think CFF should either
- pass `release-heap` only if `:os-threads` feature is present, 
- or to specify ':release-heap-ignorable t`

BTW, instead of `:release-heap :always` it's probably better to use `:release-heap :when-ok`.

**Comment by rpgoldman** [comment]
Thank you very much, Anton.  You are right; this is a CFFI issue, not an issue with CL+SSL.  I will report it there.

**Comment by luismbo** [comment]
@avodonosov passing `:release-heap :when-ok` seems sensible, as does passing `:release-heap-ignorable t`.

@rpgoldman I've fixed this via https://github.com/cffi/cffi/commit/af58df23536027e3c1d7ed3e470b380d746bfaf8. Let me know if it works for you.
