### ISSUE TITLE
make-ssl-server-stream doesn't pass a :deadline argument to ssl-server-stream

### ISSUE THREAD

**Issue by casouri** [cl-plus-ssl/cl-plus-ssl#131]
`make-ssl-server-stream` creates a stream, but doesn't set a timeout (deadline), even if the socket passed to it has a deadline. For example, hunchentoot creates a socket with a timeout, passes to cl+ssl, but the underlying stream that cl+ssl creates doesn't have timeout. That creates zombie threads in my server and deprived it of creating new threads.

**Comment by casouri** [comment]
Original conversation: https://github.com/edicl/hunchentoot/issues/189

**Comment by avodonosov** [comment]
I found an old issue #69 related to that

**Comment by casouri** [comment]
Thanks, then I'll close this one.
