### ISSUE TITLE
Avoid reloading the certificate/key?

### ISSUE THREAD

**Issue by phmarek** [cl-plus-ssl/cl-plus-ssl#132]
When I `strace` a Lisp image running `hunchentoot` with SSL, I notice that there are accesses to the SSL data files on each request.

Is there a way to tell openssl to use cached data?

**Comment by avodonosov** [comment]
It should be possible to load once into context

**Comment by phmarek** [comment]
Well, `hunchentoot` uses `cl+ssl:make-ssl-server-stream`: https://github.com/edicl/hunchentoot/blob/master/ssl.lisp#L83

Still, `strace` shows that the key-file and certificate are accessed on every incoming HTTPS access.
Do you have any suggestions how to fix that?

Apart from performance considerations it might be a nice idea to remove the key file (in a cloud environment) after starting from the (ram-based) configuration filesystem.

**Comment by avodonosov** [comment]
@phmarek , it will require creating an `acceptor` subclass and defining some hunchentoot functions for it. (Or submitting a patch to hunchentoot to enable that for the standard `ssl-acceptor`).

The acceptor will need an instance of SSL context object - create one with `cl+ssl:make-context`.
Configure the context with certificate and private key - there are several variations of OpenSSL functions that allow that: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_certificate_file.html, https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_default_passwd_cb.html (some of those functions already have FFI definitions in cl+ssl).

Define `hunchentoot:initialize-connection-stream ` for your acceptor. In this method use `cl+ssl:make-ssl-server-stream` without the `:certificate`, `:key` and `:password` parameters.

**Comment by avodonosov** [comment]
re #86

**Comment by avodonosov** [comment]
I have just added cert and key parameters to `make-context`:  903867f652df8e7bbc2ecae7fd2b827a5a100b73

And use that approach with cert and key read only once in the https server example: 903867f652df8e7bbc2ecae7fd2b827a5a100b73

**Comment by phmarek** [comment]
Great, thanks a lot!

I'll need to take a look what's needed to make (`quux-`)`hunchentoot` use that.

Thank you!

**Comment by phmarek** [comment]
I get an error in `INSTALL-KEY-AND-CERT` (https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L458), I guess because `certificate` is `nil` now in the call from `make-ssl-server-stream`.

Did you commit everything?

**Comment by avodonosov** [comment]
But `install-key-and-cert` has `(when key ...)` `(when certificate ...)`:  https://github.com/cl-plus-ssl/cl-plus-ssl/blob/735fde0145ae31fd535063b6c2d2cbd7b39ff1a6/src/streams.lisp#L261

**Comment by phmarek** [comment]
Well, this is what I get from `(TRACE "CL+SSL")`:

```
  0: (CL+SSL::CALL-WITH-GLOBAL-CONTEXT #.(SB-SYS:INT-SAP #X7FEAD0032BB0) NIL #<FUNCTION (LAMBDA NIL :IN HUNCHENTOOT:INITIALIZE-CONNECTION-STREAM) {1003A9855B}>)
    1: (CL+SSL:MAKE-SSL-SERVER-STREAM #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8092, peer: 127.0.0.1:44262" {1003D4FCE3}>)
      2: (CL+SSL:ENSURE-INITIALIZED :METHOD NIL)
        3: (CL+SSL::SSL-INITIALIZED-P)
        3: CL+SSL::SSL-INITIALIZED-P returned #.(SB-SYS:INT-SAP #X7FEAD6BC0CE0)
      2: CL+SSL:ENSURE-INITIALIZED returned NIL
;; stream buffer initialization omitted
      2: CL+SSL::INSTALL-HANDLE-AND-BIO returned 9
      2: (CL+SSL::SSL-SET-ACCEPT-STATE #.(SB-SYS:INT-SAP #X7FEAAC000B90))
      2: CL+SSL::SSL-SET-ACCEPT-STATE returned
      2: (CL+SSL::SSL-SET-CIPHER-LIST #.(SB-SYS:INT-SAP #X7FEAAC000B90) "ALL")
      2: CL+SSL::SSL-SET-CIPHER-LIST returned 1
      2: (CL+SSL::INSTALL-KEY-AND-CERT #.(SB-SYS:INT-SAP #X7FEAAC000B90) NIL NIL)
      2: CL+SSL::INSTALL-KEY-AND-CERT returned NIL
      2: (CL+SSL::SSL-STREAM-SOCKET #<CL+SSL::SSL-SERVER-STREAM for #<FD-STREAM for "socket 127.0.0.1:8092, peer: 127.0.0.1:44262" {1003D4FCE3}>>)
      2: CL+SSL::SSL-STREAM-SOCKET returned
           #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8092, peer: 127.0.0.1:44262" {1003D4FCE3}>
      2: (CL+SSL::SSL-GET-ERROR #.(SB-SYS:INT-SAP #X7FEAAC000B90) -1)
      2: CL+SSL::SSL-GET-ERROR returned 1
      2: (CL+SSL::SSL-SIGNAL-ERROR #.(SB-SYS:INT-SAP #X7FEAAC000B90) #<FUNCTION SB-IMPL::ENCAPSULATION {1008F0C31B}> 1 -1)
        3: (CL+SSL::ERR-PRINT-ERRORS-TO-STRING)
;; stuff omitted
        3: CL+SSL::ERR-PRINT-ERRORS-TO-STRING returned
             "140646575765056:error:140D9115:SSL routines:ssl_get_prev_session:session id context uninitialized:../ssl/ssl_sess.c:577:
"
```

In `hunchentoot` one of the changes is

```diff
 #-:lispworks
 (defmethod initialize-connection-stream ((acceptor ssl-acceptor) stream)
   ;; attach SSL to the stream if necessary
   (call-next-method acceptor
-                    (cl+ssl:make-ssl-server-stream stream
-                                                   :certificate (acceptor-ssl-certificate-file acceptor)
-                                                   :key (acceptor-ssl-privatekey-file acceptor)
-                                                   :password (acceptor-ssl-privatekey-password acceptor))))
+                    (cl+ssl:with-global-context ((acceptor-ssl-context acceptor))
+                      (cl+ssl:make-ssl-server-stream stream))))
 
 ;; LispWorks implementation
```

which corresponds to the `cl+ssl` example. `with-new-ssl` already does `SSL_new` from the global context, so that should be fine.

**Comment by avodonosov** [comment]
How do you initialize the global context?

What OpenSSL version do you use?

**Comment by phmarek** [comment]
Yeah, well, of course I'm making it extra complicated by using `quux-hunchentoot`.

Perhaps I should start with a plain `hunchentoot` instead....
