### ISSUE TITLE
MacOS Monterey appears to have further broken dynamic library loading

### ISSUE THREAD

**Issue by daewok** [cl-plus-ssl/cl-plus-ssl#138]
Full disclosure, I don't have a Mac running Monterey yet so I can't exhaustively test this theory. But it seems to jibe with the reports seen recently in #114, what a coworker is showing me, and [this community bug report](https://openradar.appspot.com/FB9725981).

It appears that in Monterey, calling `dlopen(3)` on a non-existent path will cause it to "helpfully" search for the missing library for you in some standard paths. The end result for cl-plus-ssl is that if MacPorts isn't installed, `dlopen("/opt/local/lib/libcrypto.dylib")` will instead be equivalent to `dlopen("libcrypto.dylib")`, insta-killing the process :(.

Given that it's Apple, we probably won't know if this is a bug or intentional for quite a while.

Sooooo, not sure what the best way forward is, but it seems like cl-plus-ssl can no longer count on throwing all the possible libcrypto and libssl paths for Darwin into the `define-foreign-library` and letting CFFI sort it all out.

**Comment by daewok** [comment]
I'm cautiously optimistic this is a bug (but even if it is, who knows when it'll be fixed). The Monterey dlopen man page includes the following:

> When path contains a slash but is not a framework path (i.e. a full path or
> a partial path to a dylib), dlopen() searches the following until it finds
> a compatible Mach-O file: $DYLD_LIBRARY_PATH (with leaf name from path ),
> then the supplied path (using current working directory for relative
> paths).

It says nothing about `DYLD_LIBRARY_PATH` having a default value, and I've confirmed it does not appear to be set by default on Monterey.

**Comment by avodonosov** [comment]
What is "not a framework path"?

**Comment by daewok** [comment]
Here's the whole searching section:

> SEARCHING
>
> dlopen() searches for a compatible Mach-O file in the directories specified
> by a set of environment variables and the process's current working
> directory.  When set, the environment variables contain a colon-separated
> list of directory paths, which can be absolute or relative to the current
> working directory.
>
> When path does not contain a slash character (i.e. it is just a leaf name),
> dlopen() searches the following until it finds a compatible Mach-O file:
> $LD_LIBRARY_PATH, $DYLD_LIBRARY_PATH, current working directory,
> $DYLD_FALLBACK_LIBRARY_PATH.
>
> When path looks like a framework path (e.g. /stuff/foo.framework/foo),
> dlopen() searches the following until it finds a compatible Mach-O file:
> $DYLD_FRAMEWORK_PATH (with framework partial path from path ), then the
> supplied path (using current working directory for relative paths).
>
> When path contains a slash but is not a framework path (i.e. a full path or
> a partial path to a dylib), dlopen() searches the following until it finds
> a compatible Mach-O file: $DYLD_LIBRARY_PATH (with leaf name from path ),
> then the supplied path (using current working directory for relative
> paths).
>
> Note: If DYLD_FALLBACK_LIBRARY_PATH is not set, dlopen operates as if
> DYLD_FALLBACK_LIBRARY_PATH was set to $HOME/lib:/usr/local/lib:/usr/lib.
>
> Note: If DYLD_FALLBACK_FRAMEWORK_PATH is not set, dlopen operates as if
> DYLD_FALLBACK_FRAMEWORK_PATH was set to
> $HOME/Library/Frameworks:/Library/Frameworks:/Network/Library/Frameworks:/System/Library/Frameworks.
>
> Note: There are no configuration files to control dlopen searching.
>
> Note: If the main executable is a set[ug]id binary or codesigned with
> entitlements, then all environment variables are ignored, and only a full
> path can be used.
>
> Note: Mac OS X uses "universal" files to combine 32-bit and 64-bit
> libraries.  This means there are no separate 32-bit and 64-bit search
> paths.

**Comment by fjl** [comment]
I think it is not a good idea in general to attempt loading openssl from all kinds of places. macOS ships with these libraries by default, so they are always available. Apple is also obligated to keep them up-to-date and resolve all security issues that may be discovered.

IMHO the only theoretical benefit of loading openssl from a non-standard location on macOS is potentially getting access to features of very recent openssl. IDK how frequent this need is.

So, it should be considered to drop alternative paths in cl-openssl and just list the OS-provided libraries.

**Comment by avodonosov** [comment]
For the record, the custom paths were added in #56.

Maybe this old problem is not relevant anymore and the custom paths can be deleted, but I hesitate changing the library behavior - don't want to bring inconvenience to people who can already depend on this.

Therefore for now I added code that checks the custom installation presence before trying it, to avoid the crash - see the commit reference above.

I'd appreciate if someone tested and confirmed it works on macOS where it previously crashed.

**Comment by mdbergmann** [comment]
I ran into this issue on Monterey yesterday, but it only happens here on M1 Mac Mini. On my Intel machine on Monterey it all works works fine.
Is this still being looked at?

**Comment by avodonosov** [comment]
I hoped it is fixed. Do you use the latest cl+ssl?

**Comment by avodonosov** [comment]
And if you sure that's the latest cl+ssl, could you trace somehow, exactly what library path it is trying to load?

For example by printing the path with `format` right above this line, if you use SBCL: https://github.com/cffi/cffi/blob/eac416d11bb483c33c277d164b4c6daccd9af452/src/cffi-sbcl.lisp#L366

**Comment by mdbergmann** [comment]
See:

```
$ sbcl
This is SBCL 2.1.9, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:update-dist "quicklisp")
You already have the latest version of "quicklisp": 2022-02-20.
NIL
* (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
..WARNING: /opt/homebrew/Cellar/sbcl/2.1.9/libexec/bin/sbcl is loading libcrypto in an unsafe way
fatal error encountered in SBCL pid 65095 pthread 0x104648580:
SIGABRT received.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
```

This is SBCL 2.1.9 however. But that's the latest available on Homebrew.

**Comment by mdbergmann** [comment]
Interestingly, it only fails on the M1 version of SBCL. Both Intel versions of CCL and SBCL can compile cl+ssl fine on the same host.

**Comment by mdbergmann** [comment]
I've added this `format`.
It tries to load the library from: '/usr/local/opt/openssl/lib/libcrypto.dylib'
But sbcl is located under 'opt/homebrew' and so the librarey to load would be: '/opt/homebrew/opt/openssl/lib/libcrypto.dylib'.

**Comment by avodonosov** [comment]
The latest version of cl+ssl only tries /usr/local/opt/openssl/lib/libcrypto.dylib if it exists. Dois it really exist on your machine?

**Comment by mdbergmann** [comment]
Does exist what?
Both actually exist.
I've migrated from an Intel machine to an M1. So '/usr/local/opt/openssl/lib/libcrypto.dylib' still exists and some programs still run from '/usr/local'.
But the new Homebrew folder is '/opt/homebrew' (on M1?), so to have the native M1 version of SBCL it is installed by the new Homebrew installation there instead.
So the native M1 SBCL build should load libcrypto from '/opt/homebrew'.

**Comment by avodonosov** [comment]
How SBCL was built does not play a role, the OpenSSL libs are not static dependencies of SBCL, they are loaded by cl+ssl Lisp code.

**Comment by avodonosov** [comment]
@mdbergmann , FYI, `define-libssl-path`, `define-libcrypto-path` can be used to customise the location of OpenSSL libs.
https://cl-plus-ssl.common-lisp.dev/#define-libssl-path

By default, the following paths are tried, in order:
https://github.com/cl-plus-ssl/cl-plus-ssl/blob/046d698cf65539faf9aba0a5ccd086a9d6f53eef/src/reload.lisp#L102

**Comment by mdbergmann** [comment]
Yeah, I know. Manually configuring the load path works. But it's inconvenient, in particular because I don't actually use cl+ssl. It's pulled by some other dependency.

It seems that the order of how the homebrew folders are tried can cause the problem if both folders exist.
Apparently SBCL M1 version from from '/opt/homebrew' can't load the Intel version from '/usr/local/opt'. It fails and doesn't continue to try to load from '/opt/homebrew/opt'. Can the dylib load error be caught somehow so that other folders are tried?
Otherwise I dunno how to solve it other than either manually removing libcrypto from '/usr/local/opt', or manually configure the load path.

**Comment by mdbergmann** [comment]
I see this is pushed to *features*.

I've added this to the `detect-macos-custom-openssl-installations` function.

```
(when (and (member :cl+ssl-homebrew-arm64-found *features*)
                    (member :cl+ssl-homebrew-found *features*))
        ;; arm64 takes precedence
        (setf *features* (remove :cl+ssl-homebrew-found *features*)))
```

It works for M1 SBCL, but fails for CCL which right now is not available to be installed to '/opt/homebrew' (only '/usr/local/'). So I think some slightly smarter way has to be found.

Is it possible to find out what is the executing compiler?

**Comment by avodonosov** [comment]
@mdbergmann, I think #180 fixes the problem you had. If both arm64 and x86-64 libs are installed, the one matching the current lisp is loaded.

**Comment by mdbergmann** [comment]
Excellent, thanks for the info.
