### ISSUE TITLE
Unwind protect seems not actually protecting

### ISSUE THREAD

**Issue by cage2** [cl-plus-ssl/cl-plus-ssl#151]
Hi!

I do not know if this is correct (for this reason i did not proposed a patch) but I noted this line that (my best guess) seems to free the memory associated with the certificate:

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L371

Should this form moved inside the `unwind-protect` (i mean after the `progn` as cleanup form) or, if not, does `unwind-protect` makes sense at all in this function?

Bye and thanks for maintaining this fundamental library!
C.

**Comment by avodonosov** [comment]
Thank you for the report. You are right, that is intended as a cleanup form.

**Comment by cage2** [comment]
On Mon, Apr 04, 2022 at 02:42:03AM -0700, Anton Vodonosov wrote:
> Closed #151 via ce3fb5771c1b19dc398614a6d63da73eae5cbee0.

Thanks!
C.
