### ISSUE TITLE
[question] free memory when error occurred creating a stream

### ISSUE THREAD

**Issue by cage2** [cl-plus-ssl/cl-plus-ssl#155]
Hi!

I am still struggling with memory issue :)

This time i stumbled upon this problem in drakma:

https://github.com/edicl/drakma/issues/118

I tried to mitigate the problem with this patch:

https://github.com/edicl/drakma/pull/119

Then digging into `cl+ssl` source i noted this comment:

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L412

Do you think this comment can be related to the `drakma`'s problem?

To be clear i am not stressing  to fix `make-ssl-client/server-stream` i even think was better that the caller was in charge to free the context instead of the two functions above, mine is just an honest question just to be sure my reasoning (and my patch!) is wrong or not.

Thanks in advance!
C.

**Comment by avodonosov** [comment]
Hi, that's an interesting report.

The firs impression:

The close-callback is called when somebody calls `close` on the cl+ssl stream object.
When the verification error happens the stack is unwound and drakma code does not get the result of `make-ssl-stream` so does not call `close` on it.

I am surprised your proposed patch to drakma fixes the problem. The  OpenSSL's `CTX` objects are reference counted, so the `auto-free-p` should not be enough. The `CTX` is also referenced from the `SSL` objects, and thus should only be freed after the `SSL` object is freed using SSL_free, which also happens in `cl+ssl:close`. So, even with your patch, there should still be a leak of the `CTX` and `SSL` objects.

If you say your patch solves the leak, then I am missing something.

**Comment by avodonosov** [comment]
I understood how `SSL` is freed - the `with-new-ssl` macro calls `ssl-free` in case of error.

**Comment by cage2** [comment]
Hi @avodonosov !

I just have to thanks a lot for you reply and truly helping me to understand what's going on. 

So now i wonder if a call to `(ssl-ctx-free ,ssl)` would be added in the macro `with-new-ssl` here:

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L387

Could this changes fix drakma's leak as well? I could try to explore this and test the results if you think it is worth the efforts.

Thanks for the interesting discussion anyway, i feel am learning a lot of new things! :)
C.

**Comment by avodonosov** [comment]
No, freeing the context here is not good, because cl+ssl has not created that context, it was created by the calling code, so the calling code should free it (in the callback it supplies or otherwise).

If we added `ssl-ctx-free` there, in the situation when the calling code does not bind new value to the `*global-context*` we would destroy the singleton context on the first error and since that cl+ssl would stop working.

I am thinking about calling the `close-callback` in case of error. But not 100% happy about it, because the the close-callback name suggests it is called when with close, while in the error situation no-one calls `(close ...)`.

**Comment by cage2** [comment]
Hi @avodonosov! 

> If we added `ssl-ctx-free` there, in the situation when the calling code does not bind new value to the `*global-context*` we would destroy the singleton context on the first error and since that cl+ssl would stop working.

Oh Yes! This totally makes sense to me!

> I am thinking about calling the close-callback in case of error. But not 100% happy about it, because the the close-callback name suggests it is called when with close, while in the error situation no-one calls (close ...).

What about adding an `:on-error-callback`?

Bye!
C.

**Comment by avodonosov** [comment]
@cage2, error-callback is an interesting idea, but we have one already, in a sense - the calling code can prepare an error handler and it will be invoked when cl+ssl signals an error.

**Comment by cage2** [comment]
Hi @avodonosov !

> error-callback is an interesting idea, but we have one already, in a sense - the calling code can prepare an error handler and it will be invoked when cl+ssl signals an error.

I totally agree! :)

Now i think the only thing left is to be reasonably sure the stream is closed in the patch for drakma.

Thanks again @avodonosov  for this interesting and useful discussion! I think this issue (even not actually an issue!) can be closed with success. :)
Bye!
C.
