### ISSUE TITLE
Getting client certificates seems to fail (null pointer?)

### ISSUE THREAD

**Issue by cage2** [cl-plus-ssl/cl-plus-ssl#158]
Hi!

I am trying to get the fingerprint of a client certificate from an ssl-stream but with no luck so far. 
I am using the function `ssl-stream-x509-certificate` but i get an error that says that the client sent no certificate at all, inspecting the stacktrace seems to me that the function above returned a null pointer, in fact. I am reasonably sure that the test client I am using (the `openssl` command line program with `-cert` and `-key` with file in pem format) is sending the certificate. I was even able to actually send some data from the client to my server after i bypassed the certificate fingerprint function. I wonder if I am using the correct function. In another program i was able, with the code you can find in the link below:

https://notabug.org/cage/tinmop/src/master/src/x509.lisp#L60

to get the fingerprint of the server's certificate, i assumed the same function worked for fetching the client's certificate (when provided of course! :)).

Sorry i have not the actual code to show, i can provide it in the next hours if needed.

Maybe is useful to know that the client certificate is self signed.

Thanks in advance!
C.

**Comment by avodonosov** [comment]
I neer did that.

All I can say is that `ssl-stream-x509-certificate` simply calls OpenSSL's ` SSL_get_peer_certificate`  or since version 3.0.0 `SSL_get1_peer_certificate`.

Checking the OpenSSL docs may help.

**Comment by avodonosov** [comment]
> A client will only send a certificate when explicitly requested to do so by the server (see [SSL_CTX_set_verify(3)](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_verify.html)).

**Comment by avodonosov** [comment]
So, it seems you need your server streams or context to use the `SSL_VERIFY_PEER`

**Comment by cage2** [comment]
Hi @avodonosov 

> So, it seems you need your server streams or context to use the `SSL_VERIFY_PEER`

Thank Anton! Again you have given me the right suggestion! :)

Exactly the constant above is needed when creating the context to get the client certificate.

The only caveat is that, if the certificate is self signed, you have to specify a callback for the `:verify` argument of `MAKE-CONTEXT` that always returns `1` otherwise an error is signaled.

I would like to add an example for this procedures to this project  as i think that someone could benefit from it if a client verification is needed (i am thinking about a gemini server, for example).

Let me know if my proposal is worth, in the meanwhile i am closing this and, obviously, thank you very much!
C.

**Comment by avodonosov** [comment]
@cage2 I agree, examples may be really helpful, please share if you will have any. We can add external links to the doc, or commit sample files to the repo.

**Comment by avodonosov** [comment]
@cage2 . BTW, one thing came to my mind., although I am not sure if that's a good idea for your purpose. Instead of adding a callback to anlow that self-signed cert, you could probably store the cert on the file system and tell OpenSSL the cert is trusted using the `SSL_CTX_load_verify_locations`: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html

**Comment by cage2** [comment]
Hi @

> @cage2 I agree, examples may be really helpful, please share if you will have any. We can add external links to the doc, or commit sample files to the repo.

Good! I am a bit busy now but i hope in a few days to file a pull request with a new example. Happy to contribute to this project even if in a minimal way! :)

Bye!
C.
