### ISSUE TITLE
Function get-peer-certificate no more available

### ISSUE THREAD

**Issue by cage2** [cl-plus-ssl/cl-plus-ssl#164]
Hi!

In the linux distribution that i use, after an upgrade, i think only libssl version 3 is available.

The function `ssl-get-peer-certificate` has been replaced by `ssl-get1-peer-certificate` and  `cl-plus-ssl` correctly addresses this fact when defining function using `cffi`.

But the function `ssl-stream-x509-certificate` 

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L289

seems that is using the missing function (`ssl-get-peer-certificate`) anyway, regardless of the libssl version.

I have patched my local copy of `cl-plus-ssl` replacing the function `ssl-stream-x509-certificate`  with the code below:

``` lisp
(defun ssl-stream-x509-certificate (ssl-stream)
  (let ((get-peer-certificate-function (if (openssl-is-at-least 3 0 0)
                                           'ssl-get1-peer-certificate
                                           'ssl-get-peer-certificate)))
    (funcall get-peer-certificate-function (ssl-stream-handle ssl-stream))))
```
the code is copied from `maybe-verify-client-stream`:

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/streams.lisp#L345

And seems to work, also i think a bit of refactoring could be useful here to remove duplicated code (`(if ((openssl-is-at-least 3 0 0) etc.)`).

Are you interested in a little patch that include this changes (assuming that my fix is correct, of course! :) )?

Bye!
C.

**Comment by avodonosov** [comment]
Hi @cage2 , sorry for the long silence - I saw the new issue on my mobile phone, but then forgot about it.

I added a fix simply based on the description. Started just by duplicating the condition, as you can see.

What kind of refactoring you have in mind, a reusable function? I am hesitating between using the `ssl-stream-x509-certificate` in the implementation of `maybe-verify-client-stream` and introducing a lower level function that accepts a `handle` as a parameter and can be used in implementations of both  `ssl-stream-x509-certificate` and `maybe-verify-client-stream`.

**Comment by avodonosov** [comment]
BTW, it would not be bad to have a unit test that calls `ssl-stream-x509-certificate` - such a test would capture the issue long ago.

**Comment by avodonosov** [comment]
As you can see, for the refactoring I went on with a lower level reusable function.

Speaking of the unit test, I though your client certificate example could be used as a basis, but maybe sometime in the future. For this issue I will probably skip the unit test.

**Comment by avodonosov** [comment]
The current tests pass, so I think the issue is completed.
Let me know if you have further ideas. 

Thank you for the report.

**Comment by cage2** [comment]
Hi @avodonosov 

> Hi @cage2 , sorry for the long silence 

No problem!

I checked your patch and you wrote exactly the same code that was in my mind! :)

Thanks for checking this report and update the code!

Bye!
C.
