### ISSUE TITLE
CFFI cannot load libraries

### ISSUE THREAD

**Issue by PF00517** [cl-plus-ssl/cl-plus-ssl#174]
I can't load CL+SSL libraries. I add library paths to *foreign-library-directories* and then try to load it via load-foreign-library, but it either does not find it at all (although the paths are correct) or writes `%1 is not a valid Win32 application`.

**Comment by avodonosov** [comment]
Try this: https://github.com/cl-plus-ssl/cl-plus-ssl#customize-shared-libraries-location

**Comment by PF00517** [comment]
If I specified those libraries correctly, it came out the same:

CL-USER> (ql:quickload :cl+ssl/config)
To load "cl+ssl/config":
  Load 1 ASDF system:
    cl+ssl/config
; Loading "cl+ssl/config"
.............
(:CL+SSL/CONFIG)
CL-USER> (cl+ssl/config:define-libssl-path "D:/OpenSSL-Win64/bin/libssl-3-x64.dll")
T
CL-USER> (cl+ssl/config:define-libcrypto-path "D:/OpenSSL-Win64/bin/libcrypto-3-x64.dll")
T
CL-USER> (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"

debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {23520049}>:
  Unable to load foreign library (LIBCRYPTO).
  Error opening shared object "D:\\OpenSSL-Win64\\bin\\libcrypto-3-x64.dll":
 %1 не является приложением Win32.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Try loading the foreign library again.
  1: [USE-VALUE                    ] Use another library instead.
  2: [TRY-RECOMPILING              ] Recompile reload and try loading it again
  3: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "cl+ssl" "src" "reload">.
  4: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "cl+ssl" "src" "reload">
                                     as having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  7:                                 Retry ASDF operation.
  8:                                 Retry ASDF operation after resetting the
                                     configuration.
  9: [ABORT                        ] Give up on "cl+ssl"
 10: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
 11:                                 Exit debugger, returning to top level.

(CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" LIBCRYPTO "Error opening shared object \"D:\\\\OpenSSL-Win64\\\\bin\\\\libcrypto-3-x64.dll\":
 %1 не является приложением Win32.")
   source: (ERROR 'LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL CONTROL
                  :FORMAT-ARGUMENTS ARGUMENTS)
0]

**Comment by avodonosov** [comment]
Maybe you are running 32 bit lisp implementation and try to load the 64 bit .dll?

Or wrong path?

For re it is diffioolt to say what is doing on.

**Comment by PF00517** [comment]
You are right. That solved the problem. Thank you!
