### ISSUE TITLE
Memory fault on interaction with trivial-ssh?

### ISSUE THREAD

**Issue by sabracrolleton** [cl-plus-ssl/cl-plus-ssl#176]
I am seeing this with both CCL 1.12.1 and SBCL 2.2.28 and 2.3.0 on a linux box using Openssh-9.1p1-3.

If I load trivial-ssh then load cl+ssl in that sequence, I can use an ssl connection with a database. (See https://github.com/marijnh/Postmodern/blob/master/cl-postgres/protocol.lisp for the call to cl+ssl:make-ssl-client-stream).

If I load cl+ssl then load trivial-ssh, I trigger memory faults trying to make the ssl connection. I have run memcheck86 on the ram chips with no errors detected, so provisionally it is not a hardware issue. I am not seeing any issue if trivial-ssh is not loaded. 

Any suggestions would be appreciated.

--- SBCL MESSAGE ---
CORRUPTION WARNING in SBCL pid 64355 tid 64355:
Memory fault at 0x7fc531954180 (pc=0x7fc531954180, fp=0x7fc5319579c0, sp=0x7fc5320b7118) tid 64355
The integrity of this image is possibly compromised.
Continuing with fingers crossed.

debugger invoked on a SB-SYS:MEMORY-FAULT-ERROR in thread
#<THREAD "main thread" RUNNING {10010A8073}>:
  Unhandled memory fault at #x7FC531954180.

--- CCL MESSAGE ---
Unhandled exception 11 at 0x7f0704fbf180, context->regs at #x7f070564e468
Exception occurred while executing foreign code
received signal 11; faulting address: 0x7f0704fbf180
invalid permissions for mapped object

Unhandled exception 11 at 0x7f8b26bbe180, context->regs at #x7f8b2724d468
Exception occurred while executing foreign code
received signal 11; faulting address: 0x7f8b26bbe180
invalid permissions for mapped object

(#x00007F8B26FE86D0) #x00003020014959C4 : #<Function SSL-CTX-NEW #x000030200149593F> + 133
(#x00007F8B26FE86E8) #x00003020014C91CC : #<Function INITIALIZE #x00003020014C8D0F> + 1213
(#x00007F8B26FE8718) #x00003020014C7E64 : #<Function ENSURE-INITIALIZED #x00003020014C7CCF> + 405
(#x00007F8B26FE8790) #x00003020014F0AE4 : #<Function MAKE-SSL-CLIENT-STREAM #x00003020014F090F> + 469

(#x00007F8B26FE8888) #x000030200421EA24 : #<Function INITIATE-SSL #x000030200421E68F> + 917
(#x00007F8B26FE88D8) #x000030200421B454 : #<Function AUTHENTICATE #x000030200421B12F> + 805
(#x00007F8B26FE8958) #x00003020042531AC : #<Function INITIATE-CONNECTION #x0000302004252AAF> + 1789
(#x00007F8B26FE8A20) #x0000302004225A64 : #<Function OPEN-DATABASE #x000030200422543F> + 1573
(#x00007F8B26FE8AA8) #x0000302004590554 : #<Anonymous Function #x00003020045904FF> + 85
(#x00007F8B26FE8AB8) #x0000300000584DB4 : #<Function TOPLEVEL-EVAL #x0000300000584A9F> + 789
(#x00007F8B26FE8B30) #x0000300000586D9C : #<Function READ-LOOP #x000030000058642F> + 2413
(#x00007F8B26FE8D78) #x000030000059298C : #<Function RUN-READ-LOOP #x00003000005928EF> + 157
(#x00007F8B26FE8DA0) #x000030000059264C : #<Function TOPLEVEL-LOOP #x00003000005925EF> + 93
(#x00007F8B26FE8DB0) #x00003000004EDACC : #<Function (:INTERNAL (TOPLEVEL-FUNCTION (LISP-DEVELOPMENT-SYSTEM T))) #x00003000004EDA5F> + 109
(#x00007F8B26FE8DD0) #x0000300000613144 : #<Function (:INTERNAL MAKE-MCL-LISTENER-PROCESS) #x0000300000612EAF> + 661
(#x00007F8B26FE8E68) #x00003000004FA4AC : #<Function RUN-PROCESS-INITIAL-FORM #x00003000004FA1DF> + 717
(#x00007F8B26FE8EF0) #x00003000004FAE44 : #<Function (:INTERNAL (%PROCESS-PRESET-INTERNAL (PROCESS))) #x00003000004FABFF> + 581
(#x00007F8B26FE8F98) #x00003000004CCB14 : #<Function (:INTERNAL THREAD-MAKE-STARTUP-FUNCTION) #x00003000004CC9FF> + 277

**Comment by avodonosov** [comment]
Using some command to see what foreign libraries are loaded into the process may help.

Probaoly when you load trivial-ssh it loads one more version of openssl, in addition to what is loaded by cl+ssl.

Then probably part of foreign calls or reference made by cl+ssl go to one openssl lib instance,  some to another instance, which results in crash.

**Comment by avodonosov** [comment]
check at two moments a least, I think:
- what libs are loaded into the process after cl+ssl is loaded
- then after trivial-ssh is loaded

**Comment by sabracrolleton** [comment]
Thank you!!

**Comment by avodonosov** [comment]
@sabracrolleton, what was it?

**Comment by sabracrolleton** [comment]
I apparently had three versions of openssl loaded. Reduced that down to one version and now cl+ssl and trivial-shell are working happily side by side.

**Comment by avodonosov** [comment]
@sabracrolleton do you know how those three versions got loaded? And how did you reduce them?
