### ISSUE TITLE
Doesn't see the library

### ISSUE THREAD

**Issue by PF00517** [cl-plus-ssl/cl-plus-ssl#177]
I'm trying to install cl+ssl but I get this error: 

* (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
..............
debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10044982F3}>:
  Unable to load any of the alternatives:
   ("libssl-1_1-x64.dll" "libssl32.dll" "ssleay32.dll")

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Try loading the foreign library again.
  1: [USE-VALUE                    ] Use another library instead.
  2: [TRY-RECOMPILING              ] Recompile reload and try loading it again
  3: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "cl+ssl" "src" "reload">.
  4: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "cl+ssl" "src" "reload">
                                     as having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  7:                                 Retry ASDF operation.
  8:                                 Retry ASDF operation after resetting the
                                     configuration.
  9: [ABORT                        ] Give up on "cl+ssl"
 10: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
 11:                                 Exit debugger, returning to top level.

(CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" ("libssl-1_1-x64.dll" "libssl32.dll" "ssleay32.dll"))
   source: (ERROR 'LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL CONTROL
                  :FORMAT-ARGUMENTS ARGUMENTS)
0]

I have the libraries installed and added to the path. What can I do?

**Comment by avodonosov** [comment]
Is OpenSSL even installed on your Windows machine?
https://github.com/cl-plus-ssl/cl-plus-ssl#windows

If it is, then maybe the default list of .dll names that cl+ssl tries does not some newer version that you have. In this case use https://github.com/cl-plus-ssl/cl-plus-ssl#customize-shared-libraries-location

If that works, let me know your .dll names, I will add it to the defaolt list. (which is here:

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/f3cee11f53fc64953ee50a754f9d162537cd0837/src/reload.lisp#L93

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/f3cee11f53fc64953ee50a754f9d162537cd0837/src/reload.lisp#L143
)

**Comment by PF00517** [comment]
(ql:quickload "cl+ssl/config")
(cl+ssl/config:define-libssl-path "D:/OpenSSL-Win64/bin/libssl-3-x64.dll")
(cl+ssl/config:define-libcrypto-path "D:/OpenSSL-Win64/bin/libcrypto-3-x64.dll")
(ql:quickload "cl+ssl")

This way everything works, but every time you have to rewrite it all.

**Comment by avodonosov** [comment]
Why rewrite every time?

**Comment by Jacobis9000** [comment]
I have this same issue in 2025. Is there any way to fix this so that I do not have to do quickload "cl+ssl/config" and instruct it where to look for the DLL's every time I want to load it?
