### ISSUE TITLE
Tests & CI Environment

### ISSUE THREAD

**Issue by deadtrickster** [cl-plus-ssl/cl-plus-ssl#23]
I'm about to propose relatively huge changes, like moving all ffi stuff to separate package.
However I'm not feeling comfortable about this considering the fact I can not test anything. 
What I'm proposing:
- [x] Choose test framework, recently I used prove, fiveam and something else. (5AM)
- [x] Choose implemenation manager, I'm using roswell, btw it integrates with prove rather well (CIM)
- [x] Setup Travis CI environment
- [ ] Actually write tests that do not depend on developer home directory name ;-)

**Comment by avodonosov** [comment]
Disadvantage of prove is that it doesn't return the failed test names, just true / false status for a whole test suite, and encourages running tests during load time. I would prefer faveam.

**Comment by deadtrickster** [comment]
I started here: https://github.com/deadtrickster/cl-plus-ssl/tree/test-ci
