### ISSUE TITLE
Free ssl when make-ssl-*-stream body fails

### ISSUE THREAD

**Issue by deadtrickster** [cl-plus-ssl/cl-plus-ssl#27]
Maybe implement fix like here https://github.com/cl-plus-ssl/cl-plus-ssl/pull/26

**Comment by deadtrickster** [comment]
Can you assign this to me?

**Comment by avodonosov** [comment]
It's necessary to have you as a member of cl-plus-ssl organization to assign tickets - I've sent you an invitation.

**Comment by deadtrickster** [comment]
Thank you for trust, however all related controls are still disabled.

**Comment by avodonosov** [comment]
I think github sent you an invitation and you need to accept it

**Comment by deadtrickster** [comment]
:-) I actually accepted it and now can see members of this organisation for example.

**Comment by deadtrickster** [comment]
Thx

**Comment by deadtrickster** [comment]
Fixed in #32
