### ISSUE TITLE
SBCL:The alien function "CRYPTO_num_locks" is undefined

### ISSUE THREAD

**Issue by equwal** [cl-plus-ssl/cl-plus-ssl#43]
`The alien function "CRYPTO_num_locks" is undefined.`
non-ssl http requests work fine. I have tried completely reinstalling quicklisp, and was unfortunately unable to resolve the problem. I have the package `openssl` installed, and I am on arch linux.

The problem appears to be with the cffi bindings that are used. I have been getting this error on `drakma` and `dexador` when attempting to get ssl pages.

**Comment by stassats** [comment]
Works fine here, your ssl must be broken.

**Comment by equwal** [comment]
I have another computer also running arch linux. It doesn't have this problem either. I am going to try reinstalling everything I can, maybe something was corrupted.

**Comment by equwal** [comment]
You were correct. I needed to install https://www.archlinux.org/packages/extra/x86_64/openssl-1.0/, in addition to the default core openssl package.
