### ISSUE TITLE
Update the URI to test SNI

### ISSUE THREAD

**Issue by libre-man** [cl-plus-ssl/cl-plus-ssl#44]
The URI to test SNI, velox.ch, does not seem to exist anymore. It should be updated to something that does exist.

**Comment by avodonosov** [comment]
Yes, I'm searching for a substitution, but can't find anything. Considering to disable these tests.

**Comment by libre-man** [comment]
If you disable the tests I think that means there are almost no tests for the streams.lisp file left. I think it would be better to at least have some tests for this file with and without verification.

**Comment by avodonosov** [comment]
What do you mean? We can disable two tests because we see no way to implement them, what else can we do?

**Comment by libre-man** [comment]
Oh sorry. Yeah we should disable them (mark them as skipped or something like that), but we should probably also add some tests that do requests to servers that implement SSL properly as a form of integration test. Especially as the SNI tests were doing this in some form.

**Comment by avodonosov** [comment]
Skipped these two tests.

As for more test coverage - probably we can do some using https://badssl.com/. (But in a separate pull request)
