### ISSUE TITLE
Memory fault when using LibreSSL

### ISSUE THREAD

**Issue by aerique** [cl-plus-ssl/cl-plus-ssl#47]
(https://www.libressl.org/)

CL+SSL gives a memory fault when using the LibreSSL library instead of OpenSSL. Since some Unixes only come with this library it can be hard to work around.  (In my case because I'm using Linux (Void Linux) I could work around it by using libssl from Steam.)

(Sorry for the silly example below but I have the same issue when using https from Drakma.)

See the reproduction path below, first the memory fault when using LibreSSL:

    15:23:04 [user@host:~/s/c/q/d/q/s/cl+ssl-20170403-git] $ sbcl
    This is SBCL 1.3.18, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    
    Linedit version 0.17.5, smart mode, ESC-h for help.
    * (ql:quickload :cl+ssl)
    To load "cl+ssl":
      Load 1 ASDF system:
        cl+ssl
    ; Loading "cl+ssl"
    .
    (:CL+SSL)
    * (with-output-to-string (s) (cl+ssl:make-ssl-client-stream s))
    CORRUPTION WARNING in SBCL pid 23167(tid 0x7ffff7fdafc0):
    Memory fault at 0x10 (pc=0x7ffff644cac7, sp=0x7ffff6ea76e8)
    The integrity of this image is possibly compromised.
    Continuing with fingers crossed.
    
    debugger invoked on a SB-SYS:MEMORY-FAULT-ERROR in thread
    #<THREAD "main thread" RUNNING {1001F16C03}>:
      Unhandled memory fault at #x10.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit debugger, returning to top level.
    
    (SB-SYS:MEMORY-FAULT-ERROR)

And then with no memory fault when using OpenSSL:

    15:25:16 [user@host:~/s/c/q/d/q/s/cl+ssl-20170403-git] $ 
    env LD_LIBRARY_PATH=/home/erikw/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu sbcl
    This is SBCL 1.3.18, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    
    Linedit version 0.17.5, smart mode, ESC-h for help.
    * (ql:quickload :cl+ssl)
    To load "cl+ssl":
      Load 1 ASDF system:
        cl+ssl
    ; Loading "cl+ssl"
    .
    (:CL+SSL)
    * (with-output-to-string (s) (cl+ssl:make-ssl-client-stream s))
    
    debugger invoked on a SIMPLE-TYPE-ERROR in thread
    #<THREAD "main thread" RUNNING {1001F16C03}>:
      #<SB-IMPL::STRING-OUTPUT-STREAM {10024AE6C3}> is not a binary output stream.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit debugger, returning to top level.
    
    (SB-KERNEL:ILL-BOUT #<SB-IMPL::STRING-OUTPUT-STREAM {10024AE6C3}>)

**Comment by avodonosov** [comment]
Maybe the same problem as yesterday closed pull request #42. Try with version from git.

**Comment by aerique** [comment]
Yes that works, thank you!
