### ISSUE TITLE
Windows libssl32.dll etc not found

### ISSUE THREAD

**Issue by autcrock** [cl-plus-ssl/cl-plus-ssl#53]
Hi and thanks for the work you do on cl+ssl.

While trying to load Ceramic on both sbcl and clozure (both 64 bits) I get problems with missing ssl DLL's.  This is coming from cl+ssl as follows:

? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
> Error: Unable to load any of the alternatives:
>           ("libssl32.dll" "ssleay32.dll")
> While executing: CFFI::FL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 >

I'm using Windows 10 64 bits.  Is there a quick fix?  I seem to only find ssl 1.1 dlls around on the web.  

Cheers,

Mike

**Comment by avodonosov** [comment]
Are you sure you have the DLLs present in your system? 09.07.2017, 01:53, "autcrock" <notifications@github.com>:Hi and thanks for the work you do on cl+ssl.While trying to load Ceramic on both sbcl and clozure (both 64 bits) I get problems with missing ssl DLL's. This is coming from cl+ssl as follows:? (ql:quickload :cl+ssl)To load "cl+ssl":Load 1 ASDF system:cl+ssl; Loading "cl+ssl"Error: Unable to load any of the alternatives:("libssl32.dll" "ssleay32.dll")While executing: CFFI::FL-ERROR, in process listener(1).Type :POP to abort, :R for a list of available restarts.Type :? for other options.1 >I'm using Windows 10 64 bits. Is there a quick fix? I seem to only find ssl 1.1 dlls around on the web.Cheers,Mike—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by autcrock** [comment]
Thanks Anton.

I don't have either of those two libraries.  I had thought that quicklisp
provided them as a binary package.

Either way, the site http://slproweb.com/products/Win32OpenSSL.html only
provides ssl version 1.x (libssl-1_x.dll) - not either of the libssl32 or
leay required by cl+ssl.

Is this because libssl32 is out of date and replaced by libssl-1_1.dll?
 (I'm a bit out of touch with SSL stuff (and Common Lisp for that matter,
not having used it since about 2005).)

If so then I'll build the libraries from old source.

Cheers

Mike

**Comment by avodonosov** [comment]
If you install the package, what DLLs it provides? 

If it provides DLLs absent here https://github.com/cl-plus-ssl/cl-plus-ssl/blob/4124b73355124eae97b2bdeeccf1e21a24fe50e3/src/reload.lisp#L28 then we can indlude these DLLs.

Please send a pull request if you make it work.

**Comment by mtstickney** [comment]
Looks like the Shining Light Productions version installs `libeay32.dll`, `libssl32.dll`, and `ssleay32.dll` for 1.0.2. When I cross-compile OpenSSL from source, it only builds `libeay32.dll` and `ssleay32.dll`.

For 1.1.0, the SL build seems to install `libssl-1_1.dll`; cross-compiling from source also seems to create a `libcrypto-1_1.dll`, although I'm not sure under what circumstances that's necessary.

@avodonosov : is `cl+ssl`'s support for OpenSSL 1.1 complete at this point (possibly including a way to detect which version to use when both are installed)? If not, the best thing to do here is to remove the 1.1 OpenSSL install, and install a 1.0 version instead.

**Comment by autcrock** [comment]
Thanks Matt and Anton.  I got it going with the 1.0.x installer as
suggested, and after a bit more work to sort cl-libev, got Ceramic running,
and also qtools.

On 10 Jul 2017 08:08, "Matthew Stickney" <notifications@github.com> wrote:

Looks like the Shining Light Productions version installs libeay32.dll,
libssl32.dll, and ssleay32.dll for 1.0.2. When I cross-compile OpenSSL from
source, it only builds libeay32.dll and ssleay32.dll.

For 1.1.0, the SL build seems to install libssl-1_1.dll; cross-compiling
from source also seems to create a libcrypto-1_1.dll, although I'm not sure
under what circumstances that's necessary.

@avodonosov <https://github.com/avodonosov> : is cl+ssl's support for
OpenSSL 1.1 complete at this point (possibly including a way to detect
which version to use when both are installed)? If not, the best thing to do
here is to remove the 1.1 OpenSSL install, and install a 1.0 version
instead.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cl-plus-ssl/cl-plus-ssl/issues/53#issuecomment-313968774>,
or mute the thread

**Comment by avodonosov** [comment]
OpenSSL 1.1 should work with cl+ssl - as far as I can tell the API we use didn't change.
@autcrock  if you ever change to OpenSSL 1.1 again, try adding the 1.1 DLLs at https://github.com/cl-plus-ssl/cl-plus-ssl/blob/4124b73355124eae97b2bdeeccf1e21a24fe50e3/src/reload.lisp#L28 and if works well - send pull request.

Best regards,
- Anton

**Comment by autcrock** [comment]
Shall do.  Hopefully this weekend Anton.

**Comment by avodonosov** [comment]
@autcrock, FYI, the 1.1 DLL names are added to cl+ssl, should work now with 1.1.

**Comment by autcrock** [comment]
Thanks Anton, I'll take a look tonight.

**Comment by autcrock** [comment]
Had a go but no success yet - I need to narrow down some potential causes.
I'll get back to it tomorrow evening.

**Comment by avodonosov** [comment]
@autcrock, no worries, it's just to let you know. Although, if you have any results, please share.

**Comment by autcrock** [comment]
Shall do.

**Comment by autcrock** [comment]
Hi again.

With some provisos the system loads correctly from your github master
branch on Windows 10 using the current official 64 bit SBCL version (1.4.x)
and the current 64 bit CCL.  The provisos are:

   1. The Shining Light DLL needs to be on the system executable path.
   2. CL+SSL does not say anything if the DLL is not on the path - which is
   counter-intuitive to me.
   3. I had a weird problem encapsulated below as a workaround git patch,
   and also by the error message further below raised by Sly under Portacle.
   I verified this problem under both CCL and SBCL.  The :~ construct is new
   to me.  It's tempting to say its a Windows line ending problem, but I
   replaced the line endings and spaces after each cipher name with ":~ " and
   got the same kind of error, but complaining about :SPACE instead!  In the
   end I just replaced the whole format statement.
   4. I was unable to run any test code.

With the patch applied I was able to load the DLL.  The patch substitutes a
space separated string of the cipher names for the format statement.  I
proved that the DLL loaded by executing this code:
===================================
CL-USER> (cl+ssl::openssl-version-num)
269488191 (29 bits, #x1010103F)
===================================

I also verified this on CCL running at the Windows 10 command prompt:

===================================
? (cl+ssl::openssl-version-num)
269488191
?
===================================


When I renamed the SSL bin directory, restarted SBCL and reloaded cl+ssl, I
got an error message when I executed (cl+ssl::openssl-version-num) as
expected.  As noted above, however, the system did not complain that it
could not find the file???

Both SBCL and CCL returned the following default cipher list after the
patch:

=================================================================================================================
CL-USER> cl+ssl::+default-cipher-list+
"ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA
ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA
ECDHE-RSA-RC4-SHA DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256
DHE-RSA-AES256-SHA DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256
DHE-RSA-AES128-SHA AES256-GCM-SHA384 AES256-SHA256 AES256-SHA
AES128-GCM-SHA256 AES128-SHA256 AES128-SHA"
CL-USER>
=================================================================================================================

I can't make any comment on whether the system works correctly once loaded
as I don't know anything about SSL.  I'm willing to probe further if you
could send me a simple, portable CL program to check the system running at
the SBCL and CCL prompts.  I couldn't get the test stuff to load and run
and haven't had time to digest the test code to understand why.

I hope this has been helpful, and thanks for your hard work on the library!

Cheers

Mike
==========================================
PS D:\source\Lisp\cl-plus-ssl> git diff
diff --git a/src/context.lisp b/src/context.lisp
index 2738485..b476eda 100644
--- a/src/context.lisp
+++ b/src/context.lisp
@@ -59,26 +59,7 @@
      (error "Invalid location ~a" location))))

 (alexandria:define-constant +default-cipher-list+
-    (format nil
-            "ECDHE-RSA-AES256-GCM-SHA384:~
-            ECDHE-RSA-AES256-SHA384:~
-            ECDHE-RSA-AES256-SHA:~
-            ECDHE-RSA-AES128-GCM-SHA256:~
-            ECDHE-RSA-AES128-SHA256:~
-            ECDHE-RSA-AES128-SHA:~
-            ECDHE-RSA-RC4-SHA:~
-            DHE-RSA-AES256-GCM-SHA384:~
-            DHE-RSA-AES256-SHA256:~
-            DHE-RSA-AES256-SHA:~
-            DHE-RSA-AES128-GCM-SHA256:~
-            DHE-RSA-AES128-SHA256:~
-            DHE-RSA-AES128-SHA:~
-            AES256-GCM-SHA384:~
-            AES256-SHA256:~
-            AES256-SHA:~
-            AES128-GCM-SHA256:~
-            AES128-SHA256:~
-            AES128-SHA") :test 'equal)
+  "ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES256-SHA ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256
ECDHE-RSA-AES128-SHA ECDHE-RSA-RC4-SHA DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES256-SHA256 DHE-RSA-AES256-SHA DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-SHA256 DHE-RSA-AES128-SHA AES256-GCM-SHA384 AES256-SHA256
AES256-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA" :test 'equal)

 (cffi:defcallback verify-peer-callback :int ((ok :int) (ctx :pointer))
   (let ((error-code (x509-store-ctx-get-error ctx)))


-----------------------------------------------------------------------------------------------
error in FORMAT: Unknown format directive (character: Return)
  ECDHE-RSA-AES256-GCM-SHA384:~

            ECDHE-RSA-AES256-SHA384:~

            ECDHE-RSA-AES256-SHA:~

            ECDHE-RSA-AES128-GCM-SHA256:~

            ECDHE-RSA-AES128-SHA256:~

            ECDHE-RSA-AES128-SHA:~

            ECDHE-RSA-RC4-SHA:~

            DHE-RSA-AES256-GCM-SHA384:~

            DHE-RSA-AES256-SHA256:~

            DHE-RSA-AES256-SHA:~

            DHE-RSA-AES128-GCM-SHA256:~

            DHE-RSA-AES128-SHA256:~

            DHE-RSA-AES128-SHA:~

            AES256-GCM-SHA384:~

            AES256-SHA256:~

            AES256-SHA:~

            AES128-GCM-SHA256:~

            AES128-SHA256:~

            AES128-SHA
                               ^
   [Condition of type SB-FORMAT:FORMAT-ERROR]

**Comment by avodonosov** [comment]
Mike, thank you for the feedback. Some comments:

>   1. The Shining Light DLL needs to be on the system executable path.

Yes    

>   2. CL+SSL does not say anything if the DLL is not on the path - which is
   counter-intuitive to me.

If the DLLs are not found an error will be signaled. I believe you have old versions of the DLLs somewhere in your path.

> When I renamed the SSL bin directory, restarted SBCL and reloaded cl+ssl, I
got an error message when I executed (cl+ssl::openssl-version-num) as
expected.  As noted above, however, the system did not complain that it
could not find the file???

(cl+ssl::openssl-version-num) only exists in new version of OpenSSL.
 Previously this function was named (cl+ssl::ssl-eay), you can try it.
Or the compatibility wrapper around these two: (cl+ssl::compat-openssl-version)

Also, (cffi:list-foreign-libraries) will show what foreign libraries you have loaded currently.

>   3. I had a weird problem encapsulated below as a workaround git patch,
   and also by the error message further below raised by Sly under Portacle.
   I verified this problem under both CCL and SBCL.  The :~ construct is new
   to me.  It's tempting to say its a Windows line ending problem, but I
   replaced the line endings and spaces after each cipher name with ":~ " and
   got the same kind of error, but complaining about :SPACE instead!  In the
   end I just replaced the whole format statement.

I think it is a windows line ending problem. It was mentioned in #80 by another user,
he says the default git Windows setup changes line endings to CRLF on checkout, and SBCL can't tolerate it in format strings. I think to add .gitattributes with  * text=false to prevent this automatic CRLF conversion.


>   4. I was unable to run any test code.

> I can't make any comment on whether the system works correctly once loaded
as I don't know anything about SSL.  I'm willing to probe further if you
could send me a simple, portable CL program to check the system running at
the SBCL and CCL prompts.

```common-lisp
(ql:quickload :drakma)
(drakma:http-request "https://google.com/")
```

>  I couldn't get the test stuff to load and run
and haven't had time to digest the test code to understand why.

If you were looking at the test.lisp, it's outdated. The current test suite can be run with

```common-lisp
(ql:quickload :cl+ssl.test)
(5am:explain! (5am:run :cl+ssl))
```

**Comment by autcrock** [comment]
Thanks Anton.

On Thu, Jun 27, 2019 at 1:33 PM Anton Vodonosov <notifications@github.com>
wrote:

> Mike, thank you for the feedback. Some comments:
>
>
>    1. The Shining Light DLL needs to be on the system executable path.
>
> Yes
>
>
>    1. CL+SSL does not say anything if the DLL is not on the path - which
>    is
>    counter-intuitive to me.
>
> If the DLLs are not found an error will be signaled. I believe you have
> old versions of the DLLs somewhere in your path.
>

Tonight the GIT source does throw the appropriate message when I rename the
SSL bin directory.  I must have made a mistake last night.


> When I renamed the SSL bin directory, restarted SBCL and reloaded cl+ssl, I
> got an error message when I executed (cl+ssl::openssl-version-num) as
> expected. As noted above, however, the system did not complain that it
> could not find the file???
>
> (cl+ssl::openssl-version-num) only exists in new version of OpenSSL.
> Previously this function was named (cl+ssl::ssl-eay), you can try it.
> Or the compatibility wrapper around these two:
> (cl+ssl::compat-openssl-version)
>
> Also, (cffi:list-foreign-libraries) will show what foreign libraries you
> have loaded currently.
>

Thanks for those tips they worked well.  I saw the 1.1 DLL's loaded
correctly.  The 5am test and the Drakma test both worked perfectly,


>    1. I had a weird problem encapsulated below as a workaround git patch,
>    and also by the error message further below raised by Sly under
>    Portacle.
>    I verified this problem under both CCL and SBCL. The :~ construct is
>    new
>    to me. It's tempting to say its a Windows line ending problem, but I
>    replaced the line endings and spaces after each cipher name with ":~ "
>    and
>    got the same kind of error, but complaining about :SPACE instead! In
>    the
>    end I just replaced the whole format statement.
>
> I think it is a windows line ending problem. It was mentioned in #80
> <https://github.com/cl-plus-ssl/cl-plus-ssl/pull/80> by another user,
> he says the default git Windows setup changes line endings to CRLF on
> checkout, and SBCL can't tolerate it in format strings. I think to add
> .gitattributes with * text=false to prevent this automatic CRLF conversion.
>

You were right.  I couldn't make the above suggestion work without going
down a rabbit hole, so in the end I edited the string in Notepad++ to just
remove the CR's in the string and saved, which worked perfectly.  See
attached picture:

[image: Capture.PNG]


If you don't mind me asking, what do you use Common Lisp for?

I hope that Lisp will survive, it's a good language, but I am amazed that
anyone uses it at all anymore.  People mostly don't like unusual things.

Cheers

Mike Thomas

**Comment by avodonosov** [comment]
For general purpose programming. I implemented several personal projects. Or when I need to code something quickly. There are more unusual languages than CL and some people still use them :)

I learned CL because I was eager to learn more about programming. And now, an advantage of CL for me is that I know it already.
