### ISSUE TITLE
On OSX default libssl is sub-optimal?

### ISSUE THREAD

**Issue by jtkifa** [cl-plus-ssl/cl-plus-ssl#56]
I was having problems with likely missing TLS 1.2 support until I changed
reload.lisp to have

_(cffi:define-foreign-library libssl
  (:darwin (:or 
              **"/opt/local/lib/libssl.dylib"** ;; this is new - default OSX libssl does not support TLS 1.2?
              ;; perhaps want the openssl in homebrew  here too ?
              "libssl.dylib" "/usr/lib/libssl.dylib"))_

In particular, I couldn't load https://ssd.jpl.nasa.gov/horizons.cgi in drakma

**Comment by avodonosov** [comment]
I don't know what is the default libssl on OSX. 

What error message do you have when loading https://ssd.jpl.nasa.gov/horizons.cgi in drakma?

**Comment by jtkifa** [comment]
The message is: 

`error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

and when loading one sees:

style-warning: Undefined alien: "TLSv1_1_client_method"
style-warning: Undefined alien: "TLSv1_1_server_method"
style-warning: Undefined alien: "TLSv1_1_method"
style-warning: Undefined alien: "TLSv1_2_client_method"
style-warning: Undefined alien: "TLSv1_2_server_method"
style-warning: Undefined alien: "TLSv1_2_method"

It happens when cl+ssl loads /usr/lib/libssl.dylib instead of macports version /opt/local/lib/libssl.dylib

Perhaps there could be an (environment) variable to override the library?

(cffi:define-foreign-library libssl
  (:windows (:or 
      (if (boundp 'cl::*cl+ssl-libssl*) cl::*cl+ssl-libssl*)
      "libssl32.dll" "ssleay32.dll"))
  (:darwin (:or 
              (if (boundp 'cl::*cl+ssl-libssl*) cl::*cl+ssl-libssl*)
             "/opt/local/lib/libssl.dylib"
		"libssl.dylib"
		"/usr/lib/libssl.dylib")) ...

**Comment by avodonosov** [comment]
Having a variable to specify library path would be good, but I don't understand how to correctly pass it to `cffi:define-foreign-library`.

The example you provide, have you tried how it works?

CFFI doesn't seem to allow expressions in the `define-foreign-library`. See the description of library-designator: https://common-lisp.net/project/cffi/manual/html_node/load_002dforeign_002dlibrary.html#load_002dforeign_002dlibrary

**Comment by luismbo** [comment]
FTR, I've tried to answer this question here: https://mailman.common-lisp.net/pipermail/cffi-devel/2017-September/003035.html

**Comment by avodonosov** [comment]
@jtkifa , @luismbo 

Now if the `*features*` flag `:cl+ssl-foreign-libs-already-loaded`is specified, the cl+ssl doesn't load the foreign library(-ies) itself, assuming the user has already loaded the version he needs:

```common-lisp
        (cffi:load-foreign-library "/opt/local/lib/libssl.dylib")

        (let ((*features* (cons :cl+ssl-foreign-libs-already-loaded
                                *features*)))
          (ql:quickload :cl+ssl :verbose t))
```

**Comment by jtkifa** [comment]
Hi Anton,

Thank you for fixing this issue.   

Do you think that in reload.lisp it might be good to do something like the following for the Darwin case, so even the default case works better?
The other Unixes seem to have lots of special case libssl loading too.



(cffi:define-foreign-library libssl
  ;;
  (:windows (:or "libssl32.dll" "ssleay32.dll”))
  ;; 
  ;; the default OS-X libssl seems have had insufficient crypto algos (missing TLSv1_[1,2]_XXX methods)
  ;; so first try to load possible custom installations of libssl
  (:darwin (:or "/opt/local/lib/libssl.dylib” ;; MacPorts
                “/sw/lib/libssl.dylib”        ;; Fink
                “/usr/local/lib/libssl.dylib” ;; Homebrew and personalized install
                “libssl.dylib”                ;; default system libssl, which may have insufficient crypto
                "/usr/lib/libssl.dylib"))



Jan

**Comment by avodonosov** [comment]
I think that makes sense, added that.
