### ISSUE TITLE
cl+ssl fails to build on OpenBSD 6.2

### ISSUE THREAD

**Issue by trinque** [cl-plus-ssl/cl-plus-ssl#57]
It appears that the version of libressl in OpenBSD 6.2 uses a new function, "freezero", which cannot be found by cffi.

```
* (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
.sbcl:/usr/lib/libcrypto.so.42.0: undefined symbol 'freezero'

debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10028CE583}>:
  Unable to load foreign library (LIBCRYPTO).
  Error opening shared object "libcrypto.so":
  Cannot load specified object.
```

**Comment by avodonosov** [comment]
@trinque, it looks like its not CFFI who is failing to find the function, but native system linker can find the "freezero" object linked from libcrypto.so.

Can you confirm that?

Where does the "freezero" come from when you start openssl in command line?

**Comment by trinque** [comment]
openssl can indeed be run from the command line. freezero is present in the OpenBSD libc http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libc/stdlib/malloc.c?rev=1.234&content-type=text/x-cvsweb-markup

**Comment by avodonosov** [comment]
cl+ssl doesn't refer `freezero`. It must be something with your environment. Either your libcrypto.so doesn't specify a dependency on a library exporting `freezero`, or the search path in the system doesn't contain this library, or something similar.

**Comment by trinque** [comment]
I'm using a bare install of OpenBSD 6.2, and freezero is defined in the operating system's libc.

**Comment by avodonosov** [comment]
So why doesn't it link successfully?

**Comment by avodonosov** [comment]
@trinque, try simpler case

```common-lisp
(cffi:load-foreign-library "libcrypto.so"))
```
That way cl+ssl is ruled out, you work with pure CFFI. But CFFI just passes "libcrypto.so" to the OS loader. 

The text 
```
.sbcl:/usr/lib/libcrypto.so.42.0: undefined symbol 'freezero'
```
seem to be printed by the natve loader.

If passing the argument directly to the native fails, CFFI does search in `cffi:*foreign-library-directories*` with `cl:probe-file` and if found, passes the absolute path to the native loader.
https://common-lisp.net/project/cffi/manual/html_node/load_002dforeign_002dlibrary.html

To me, it seems like the the second part is not happening in your case. You can check it by inspecting `*foreign-library-directories*`, or by setting breakpoints in `cffi:load-foreign-library`.

**Comment by avodonosov** [comment]
On linux there are tools to study dependencies of .so files.

For example
```
$ ldd /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 
	linux-vdso.so.1 =>  (0x00007fff3d74d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6297513000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f629714a000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e51de99000)
``` 
As you see, my libcrypto explicitly specifies dependency on libc. Does your libcrypto specify that too.

BTW, only on OpenBSD cl+ssl code needs to explicitly load libcrypto. On other systems, libssl depends on libcrypto, so the loader loads it automatically using the dependencies specified in libssl.

**Comment by avodonosov** [comment]
@trinque, have you sopved the problem?

**Comment by avodonosov** [comment]
Closing the issue as outdated.

If anyone faces the issue, please investigate as explained above.

As a workaround, you can load the missing dependencies yourself before loading cl+ssl.

If you load all native libraries yourself, flag `:cl+ssl-foreign-libs-already-loaded` can be set in `*features*` to tell cl+ssl to not attempt foreign libraries loading:

```common-lisp

        (cffi:load-foreign-library "libssl.so.1.0.0")

        (let ((*features* (cons :cl+ssl-foreign-libs-already-loaded
                                *features*)))
          (ql:quickload :cl+ssl))
```
