### ISSUE TITLE
CL+SSL on CCL/MS Windows cannot load SSL DLLs

### ISSUE THREAD

**Issue by Symbolics** [cl-plus-ssl/cl-plus-ssl#58]
I have read the other two issues related to windows and wonder if anyone has this working? I've installed the 1.0.2 version of SSL, as mentioned in #53, but still no joy. Not even when naming is specifically at the restart:

Error opening shared library C:\OpenSSL-Win32\libssl32.dll : %1 is not a valid Win32 application

This happens with all combinations of '/' and '\'. I noticed in the [to-do](https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/todo.txt) mention of "Fix CCL crash".

Any suggestions? Does CL+SSL work with CCL on other platforms? Not that I can switch, but at least eliminating on possibility. Happy to help debug this combination.

**Comment by avodonosov** [comment]
It should worj well. Something is wrong with your C:\OpenSSL-Win32\libssl32.dll. Windows linker seem to be complaining. Maybe 32bit vs 64bit?

**Comment by Symbolics** [comment]
Huh. It just starting working. No reboot or anything, just a restart of CCL/emacs. Closing issue.
