### ISSUE TITLE
New failure  in openssl 1.1.0 code

### ISSUE THREAD

**Issue by xach** [cl-plus-ssl/cl-plus-ssl#63]
I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/cl+ssl/369d0f35871d00c37f059a08cf9568c9f585b516/cl+ssl-20180228-git/src/ffi-1.1.0.lisp
    ; in:
    ;      DEFINE-SSL-FUNCTION ("SSL_CTX_set_default_verify_dir" SSL-CTX-SET-DEFAULT-VERIFY-DIR)
    ;     ("SSL_CTX_set_default_verify_dir" SSL-CTX-SET-DEFAULT-VERIFY-DIR)
    ;
    ; caught ERROR:
    ;   illegal function call

    ;     (CTX :POINTER)
    ;
    ; note: deleting unreachable code

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/cl+ssl/369d0f35871d00c37f059a08cf9568c9f585b516/cl+ssl-20180228-git/src/ffi-1.1.0.lisp
    ; in:
    ;      DEFINE-SSL-FUNCTION ("SSL_CTX_set_default_verify_file" SSL-CTX-SET-DEFAULT-VERIFY-FILE)
    ;     ("SSL_CTX_set_default_verify_file" SSL-CTX-SET-DEFAULT-VERIFY-FILE)
    ;
    ; caught ERROR:
    ;   illegal function call

    ;     (CTX :POINTER)
    ;
    ; note: deleting unreachable code

**Comment by avodonosov** [comment]
Thanks, indeed a mistake, will fix today or tomorrow. Will need to add this asdf system   to Travis CI...

**Comment by avodonosov** [comment]
Fixed
