### ISSUE TITLE
The alien function "CRYPTO_num_locks" is undefined

### ISSUE THREAD

**Issue by whatacold** [cl-plus-ssl/cl-plus-ssl#64]
Hi,

`dex:get` raises an undefined function error when getting a https URL,
for example(see https://github.com/fukamachi/dexador/issues/49):

    (defvar *url* "https://lispcookbook.github.io/cl-cookbook/web-scraping.html")
    (defvar *html* (dex:get *url*))

So does drakma:

    * (drakma:http-request "https://lisp.org/")
    
    debugger invoked on a SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR in thread
    #<THREAD "main thread" RUNNING {1001F165F3}>:
      The alien function "CRYPTO_num_locks" is undefined.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit debugger, returning to top level.
    
    ("undefined function")
    0] 

What's shared here is that they both depend on cl+ssl, and the error is raised by cl+ssl.

I use sbcl with openssl 1.1.0g:

    # dnf list installed openssl-libs openssl
    Installed Packages
    openssl.x86_64                                                         1:1.1.0g-1.fc26                                                    @updates
    openssl-libs.x86_64                                                    1:1.1.0g-1.fc26                                                    @updates
    $ cat /proc/`pidof sbcl`/maps | grep -i cryp
    7fffefaa9000-7fffefd09000 r-xp 00000000 08:08 2649886                    /usr/lib64/libcrypto.so.1.1.0g
    7fffefd09000-7fffeff08000 ---p 00260000 08:08 2649886                    /usr/lib64/libcrypto.so.1.1.0g
    7fffeff08000-7fffeff25000 r--p 0025f000 08:08 2649886                    /usr/lib64/libcrypto.so.1.1.0g
    7fffeff25000-7fffeff31000 rw-p 0027c000 08:08 2649886                    /usr/lib64/libcrypto.so.1.1.0g

After checking the sources of openssl, I guess it's due to the changing of openssl implementation.
`CRYPTO_num_locks` is a macro in openssl v1.1.0:

    openssl-1.1.0g $ ag CRYPTO_num_locks
    CHANGES
    11112:  *) New function "CRYPTO_num_locks" that returns CRYPTO_NUM_LOCKS.
    
    include/openssl/crypto.h
    220:#  define CRYPTO_num_locks()            (1)

vs a function in openssl v0.9.6:

    openssl-0.9.6 $ ag CRYPTO_num_locks
    .
    .
    .
    crypto/crypto.h
    291:int CRYPTO_num_locks(void); /* return CRYPTO_NUM_LOCKS (shared libs!) */
    
    crypto/cryptlib.c
    161:int CRYPTO_num_locks(void)
    
    CHANGES
    2129:  *) New function "CRYPTO_num_locks" that returns CRYPTO_NUM_LOCKS.

**Comment by avodonosov** [comment]
What OS it is?
In some OpenSSL distributions libcrypto is a separate module. See how libraries are loaded: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/reload.lisp.


As a quick workaround you can load libcrypto yourself 

```common-lisp
 (cffi:load-foreign-library "/maybe/absolute/path/libcrypto.so.1.1.1")
```

**Comment by avodonosov** [comment]
What? CRYPTO_num_locks is a macro now? :/

**Comment by avodonosov** [comment]
Well. Patches are welcome. And thanks again to OpenSSL for breaking compatibility without need.

**Comment by whatacold** [comment]
> What OS it is?

it's fedora 26.

> What? CRYPTO_num_locks is a macro now?

Yeah, so does `CRYPTO_set_locking_callback`:

    #  define CRYPTO_num_locks()            (1)
    #  define CRYPTO_set_locking_callback(func)
    #  define CRYPTO_get_locking_callback()         (NULL)
    #  define CRYPTO_set_add_lock_callback(func)
    #  define CRYPTO_get_add_lock_callback()        (NULL)

And `CRYPTO-set-id-callback` is completely removed.

I don't know how to fix this yet,
but just workaround it by removing those 3 related functions in `ffi.lisp`, for personal usage :)

**Comment by ralt** [comment]
Hi there,

I went somewhere with a wrapper file (i.e. `(:cffi-wrapper-file "ffi-wrapper")` + `:defsystem-depends-on ("cffi-grovel")` in the asd):

```
(in-package :cl+ssl)

(c "
#include <stddef.h>
int CRYPTO_num_locks() { return 1; }
void CRYPTO_set_locking_callback(void* func) {}
int CRYPTO_get_locking_callback() { return NULL; }
void CRYPTO_set_add_lock_callback(void* func) {}
int CRYPTO_get_add_lock_callback() { return NULL; }
int CRYPTO_set_id_callback(void *func) {}
int CRYPTO_get_id_callback() { return NULL; }
int CRYPTO_thread_id() { return 0UL; }
void SSL_load_error_strings() {}
int SSL_library_init() { return 0; }
"
 )
```

And it keeps complaining about new missing functions. It feels like I'm starting to make CL+SSL actually incompatible with whatever openssl is providing, so it's not just a matter of missing functions, it's a matter of actually rewriting things to make them work.

I've upgraded to Fedora 29, which upgraded to openssl 1.1.1.

Not sure what to make out of this, I guess just a warning to other people: CL+SSL is currently very much incompatible with openssl 1.1.1.

I'm very much open to being corrected.

**Comment by osktyn** [comment]
Is there a manual fix for this? Downgrading openssl often breaks lots of other things.

**Comment by ralt** [comment]
Fedora offered an older openssl compatibility package, which I could install to make it work.

**Comment by avodonosov** [comment]
People also report LibreSSL is not ad destructive in backward compatibility as OpenSSL, and works with cl+ssl

**Comment by cmoore** [comment]
If like me you updated to FreeBSD 12.0 and are feeling stuck, as a temporary fix you can put `cl-plus-ssl` into `~/quicklisp/local-projects`, edit `src/reload.lisp` and change line 51 to

    ((and :unix (not :cygwin)) (:or "libssl.so.9"))

and finally, `pkg install openssl` which installs `1.0.2p_1` of openssl.

**Comment by osktyn** [comment]
I'm on Arch, so I'll try modifications of the suggestion above and report back,

**Comment by avodonosov** [comment]
If you want to load foreign the library yourself, you can use :CL+SSL-FOREIGN-LIBS-ALREADY-LOADED (https://common-lisp.net/project/cl-plus-ssl/)

**Comment by shamazmazum** [comment]
@ralt No, openssl 1.1.1 is not incompatible with previous versions in API sense. This is my quick and dirty solution that fixes the problem:

https://gist.github.com/shamazmazum/2ba7f2515a9cd1979fe6738566190d6c

**Comment by javierwilson** [comment]
Installing compat-openssl10 fixed this for me (on Fedora)

**Comment by avodonosov** [comment]
@javierwilson, the latest cl+ssl doesn't have this problem, you could have just uodated quicklisp.

**Comment by commander-trashdin** [comment]
I just tried it out and I'm still having this problem. OpenSSL was the latest version already, as well as pretty much everything else on my Debian, sbcl included.

**Comment by avodonosov** [comment]
@commander-trashdin , what Quicklisp version do you use? Most likely you need to upgrade Quicklisp dist.

Our Travis CI build includes many OpenSSL version, it passes: https://travis-ci.org/github/cl-plus-ssl/cl-plus-ssl/builds/696541147

**Comment by commander-trashdin** [comment]
`CL-USER> (ql:update-client)
The most up-to-date client, version 2020-01-04, is already installed.
T
CL-USER> (ql:update-all-dists)
3 dists to check.
You already have the latest version of "org.borodust.bodge": 20200320212220.
You already have the latest version of "quicklisp": 2020-06-10.
You already have the latest version of "shirakumo": 2020.06.30_18-12-12-GMT.
NIL
CL-USER> `

**Comment by avodonosov** [comment]
Try also `rm -rf ~/.cache/common-lisp/`

If that still fails, how do you try? What is the backtrace? What does `(cl+ssl::compat-openssl-version)` return?

**Comment by avodonosov** [comment]
Also please check what shared libraries are actually loaded. For example `lsof -p <sbcl pid>`

**Comment by commander-trashdin** [comment]
DId the cache clear.

`(ql:quickload 'dexador)`
`(dex:get "https://api.weather.yandex.ru/v2/informers?")`
```
The alien function "CRYPTO_num_locks" is undefined.
   [Condition of type SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR]

Restarts:
 0: [RETRY-REQUEST] Retry the same request.
 1: [RETRY] Retry SLY mREPL evaluation request.
 2: [*ABORT] Return to SLY's top level.
 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {10044CD763}>)

Backtrace:
 0: ("undefined function")
 1: (CL+SSL::INITIALIZE :METHOD #<unavailable argument> :RAND-SEED #<unavailable argument>)
 2: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CL+SSL:ENSURE-INITIALIZED))
 3: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
 4: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CL+SSL:ENSURE-INITIALIZED) {7F8DE621535B}> #<SB-THREAD:MUTEX "SSL initialization" owner: #<SB-THREAD:THREA..
 5: (CL+SSL:ENSURE-INITIALIZED :METHOD #<unavailable argument> :RAND-SEED #<unavailable argument>)
 6: ((LABELS DEXADOR.BACKEND.USOCKET::MAKE-NEW-CONNECTION :IN DEXADOR.BACKEND.USOCKET:REQUEST) #<QURI.URI.HTTP:URI-HTTPS https://api.weather.yandex.ru/v2/informers?>)
 7: (DEXADOR.BACKEND.USOCKET:REQUEST #<unavailable argument> :METHOD :GET)
 8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEXADOR:GET "https://api.weather.yandex.ru/v2/informers?") #<NULL-LEXENV>)
 9: (EVAL (DEXADOR:GET "https://api.weather.yandex.ru/v2/informers?"))
```
Okay, let's check the version `(cl+ssl::compat-openssl-version)`
Sly gives the hint of it's existence, but:
```
The function CL+SSL::COMPAT-OPENSSL-VERSION is undefined.
   [Condition of type UNDEFINED-FUNCTION]

Restarts:
 0: [CONTINUE] Retry using CL+SSL::COMPAT-OPENSSL-VERSION.
 1: [USE-VALUE] Use specified function
 2: [RETRY] Retry SLY mREPL evaluation request.
 3: [*ABORT] Return to SLY's top level.
 4: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {10044CD763}>)

Backtrace:
 0: (SB-IMPL::RETRY-%COERCE-NAME-TO-FUN CL+SSL::COMPAT-OPENSSL-VERSION NIL)
 1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CL+SSL::COMPAT-OPENSSL-VERSION) #<NULL-LEXENV>)
 2: (EVAL (CL+SSL::COMPAT-OPENSSL-VERSION))
```

**Comment by avodonosov** [comment]
> The function CL+SSL::COMPAT-OPENSSL-VERSION is undefined.

That's some very ancient cl+ssl. Maybe from one of you other dists?

**Comment by commander-trashdin** [comment]
Omg, I found a traitor in my local projects. I deleted it and now it seems okay. I'm sorry, this is so stupid.

**Comment by avodonosov** [comment]
not stupid, happens from time to time
