### ISSUE TITLE
Hang on TCP reset under SBCL on windows

### ISSUE THREAD

**Issue by mtstickney** [cl-plus-ssl/cl-plus-ssl#66]
On windows, if a socket has been closed with a TCP reset, `sb-sys:wait-until-fd-usable` will never return (this may or may not be fixable). As a consequence, if `ensure-ssl-funcall` receives a want-read error and calls `input-wait`, the call will hang with a busy-loop and never complete.

I've seen this happen intermittently with a server project; I'm haven't tested it with cl+ssl yet, but I'm pretty sure it goes something like this: establish an SSL stream to the server, have the server reset-close the socket[1] after the stream has been established, then try to read data in the client.

I don't understand the OpenSSL the IO model very well; it seems like in this case, `ensure-ssl-funcall` calls `ssl-read`, which goes through OpenSSL and eventually calls the BIO callbacks to read raw data from the socket. The `lisp-read` callback eats `end-of-file` errors, but I'm not sure what triggers OpenSSL to return a want-read error, so I don't if that's problematic or not.

[1] Getting a reset-close to happen is a bit tricky, and requires code like the following:
````lisp
(sb-alien:define-alien-type nil
    (struct linger
            (on-off (sb-alien:unsigned 16))
            (time (sb-alien:unsigned 16))))

(defstruct linger-opt
  (on-off nil :type boolean)
  (timeout 0 :type (unsigned-byte 16)))

(defun foreign-to-linger-opt (buffer size)
  (assert (= size (sb-alien:alien-size (struct linger) :bytes)))
  (make-linger-opt :on-off (not (zerop (sb-alien:slot buffer 'on-off)))
                   :timeout (sb-alien:slot buffer 'time)))

(defconstant +so-linger+ #x80)
(sb-bsd-sockets::define-socket-option
    %sockopt-linger
    nil
  sockint::sol-socket
  +so-linger+
  (struct linger)
  nil
  foreign-to-linger-opt
  sb-alien:addr)

(defun sockopt-linger (socket)
  (%sockopt-linger socket))

(defun (setf sockopt-linger) (val socket)
  (check-type val linger-opt)
  (sb-alien:with-alien ((linger (struct linger)))
    (setf (sb-alien:slot linger 'on-off) (if (linger-opt-on-off val) 1 0)
          (sb-alien:slot linger 'time) (linger-opt-timeout val))
    (setf (%sockopt-linger socket) linger)
    val))

(defun use-hard-close! (sock)
  (check-type sock usocket:stream-usocket)
  (setf (sockopt-linger (slot-value sock 'usocket::socket))
        (make-linger-opt :on-off t :timeout 0)))

(defun accept-for-reset (server-sock)
  (let ((sock (usocket:socket-accept server-sock :element-type '(unsigned-byte 8))))
    (use-hard-close! sock)
    sock))

;;; Example usage:
;; Set up an SSL stream
(setf *con* (accept-for-reset *server-sock*)
      *ssl-con* (cl+ssl:make-ssl-server-stream (usocket:socket-stream *con*)))
;; Now abort-close it.
(close (usocket:socket-stream *con*) :abort t)
````

**Comment by mtstickney** [comment]
Actually, after some testing, the procedure to reproduce is a little different:
1. Connect to the server and establish an ssl stream on both ends
2. Perform a read on the client (`read-byte`) will do
3. Abort-close the stream on the server.

If you perform the read after the connection has been reset, you'll get a normal IO error.

**Comment by mtstickney** [comment]
There's also a secondary issue that even with a working `sb-sys:wait-until-fd-usable`, that polls the socket for input; if you initiate a read on the ssl stream before data is available, it will consume an entire cpu core until the data becomes available.

It seems like most of this would be better by just using blocking reads in the BIO functions to begin with, instead of `listen`/`input-wait`. Was there a reason to use those instead of regular blocking reads?

**Comment by mtstickney** [comment]
Ok, I think I see now: the {input,output}-waiting was added as part of implementing support for IO deadlines, which requires the BIO to be used in non-blocking mode, which causes openssl to do the whole want-read thing. It looks like this isn't triggered if a stream is passed with `:unwrap-streams-p nil`, so that's an application-level workaround for the problem.

I think this is something that should be fixed in SBCL; the only thing I can think of that could be changed in cl+ssl itself is to avoid doing an input-wait if the stream deadline is still `nil`, since there's no need to avoid blocking in that case anyway.

**Comment by hineios** [comment]
I've been struggling with this myself lately.
I noticed this occuring while running some nmap ssl scripts against the server, and I have been trying to debug it for longer than I care to admit 😄 

@mtstickney I assume there has been no development in the SBCL side of things, given that I continue to get the same behaviour you describe, right?
Has an issue been reported or something?
Or is this expected to behave this way from SBCL's point of view?

**Comment by mtstickney** [comment]
@hineios There has, sort of. I submitted a patch for it back in 2018[1], and the devs said "this is fiddly, we'd like a test please" and, well, I haven't gotten around to writing the test yet. The problem is that writing the test involves adding support for the SO_LINGER sockopt, which itself is going to require a test and doc updates. This has been on my to-do list for a long time, but I've never gotten around to it. It's not that hard, I've just had other things to do.

Looking at it now, the patch I sent to the mailing list seems a little odd in some places, but I will say that I ran it in production without any problems, so for now you may want to make yourself a patched version of sbcl to use  (but use the second patch in that thread, the first one's busted).

[1] https://sourceforge.net/p/sbcl/mailman/sbcl-devel/thread/CAKH_Ld7T88QN1ey%2BEMYKZVGGgwvvxxxXJLxZwWpheR8St5Ck_g%40mail.gmail.com/#msg36356672

**Comment by hineios** [comment]
I'm already running a patched version of SBCL, incorporating your patch might well be a solution.

Thank you so much for your response.
I'll give it a whirl and I can probably muster some effort in helping with the patch and documentation. ;)

**Comment by hineios** [comment]
Well, your patch does solve the problem @mtstickney 🎉 
Thank you so much.
I'll try and make that test that Christophe Rhodes was asking for, so your fix can finally be merged.
(should you have any comments/advice I'd appreciate them, just drop me an email)

Since this isn't related to CL+SSL, maybe we can close this issue, don't you think @avodonosov ?

**Comment by avodonosov** [comment]
The https://github.com/mtstickney/sbcl/issues/1 says "merged upstream", @hineios confirms the patch solves the problem. 

Closing the issue.

Thank you, @hineios and especially @mtstickney
