### ISSUE TITLE
Crash in saved images

### ISSUE THREAD

**Issue by fiddlerwoaroof** [cl-plus-ssl/cl-plus-ssl#67]
`cl+ssl:make-context` doesn't work when it's called from a dumped image, if it was called before the image was dumped.  Calling `cl+ssl::ssl-library-init` in the main function fixes the error.

```
% sbcl --no-userinit \
     --load ~/quicklisp/setup.lisp \
     --eval '(ql:quickload :cl+ssl)' \
     --eval '(cl+ssl:make-context)' \
     --eval '(terpri)' \
     <<EOF
(save-lisp-and-die "/tmp/foobar"
                   :executable t
                   :toplevel (lambda () (cl+ssl:make-context)))
EOF

# <snip>

% /tmp/foobar

debugger invoked on a CL+SSL:SSL-ERROR-INITIALIZE in thread
#<THREAD "main thread" RUNNING {10006385B3}>:
  SSL initialization error: Can't create new SSL CTX
SSL error queue:
error:140A90F2:lib(20):func(169):reason(242)


Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(CL+SSL:MAKE-CONTEXT :METHOD NIL :DISABLED-PROTOCOLS NIL :OPTIONS NIL :SESSION-CACHE-MODE 2 :VERIFY-LOCATION :DEFAULT :VERIFY-DEPTH 100 :VERIFY-MODE 1 :VERIFY-CALLBACK NIL :CIPHER-LIST #<(SIMPLE-BASE-STRING 383) ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-RC4-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AE... {1000B4235F}> :PEM-PASSWORD-CALLBACK CL+SSL::PEM-PASSWORD-CALLBACK)
   source: (ERROR 'SSL-ERROR-INITIALIZE :REASON "Can't create new SSL CTX"
                  :QUEUE (READ-SSL-ERROR-QUEUE))
0]

%
```

```
% sbcl --no-userinit \                                                                                                                                          -- INSERT --
     --load ~/quicklisp/setup.lisp \
     --eval '(ql:quickload :cl+ssl)' \
     --eval '(cl+ssl:make-context)' \
     --eval '(terpri)' \
     <<EOF
(save-lisp-and-die "/tmp/foobar"
                   :executable t
                   :toplevel (lambda () 
                               (cl+ssl::ssl-library-init)
                               (cl+ssl:make-context)))
EOF
% /tmp/foobar

%
```

**Comment by mtstickney** [comment]
This is probably because the `make-context` call sets `*global-ssl-context*` and `*global-ssl-method*`, which cause the library to assume it's been initialized. Those variables retain their contents when dumped, so the library assumes it's still initialized when you call `make-context` in the image, but the freshly-loaded ssl library needs to be re-initialized.

I'm not sure that foreign objects survive a dump (or that the pointers to them are still valid if they do), so storing foreign objects in those variables might be unsafe for other reasons. I'm not aware of a way for the library to make sure those variables are un-set on dump automatically; this may be something that has to be handled at the application level.

Fortunately, that's pretty easy: call `ssl-library-init`as you do, or start your toplevel function with
````lisp
(let ((cl+ssl::*global-ssl-method* nil)
       (cl+ssl::*global-ssl-context* nil))
;;<your code>
)
````
or set one/both of those vars to `nil` before you call `save-lisp-and-die`.

**Comment by fiddlerwoaroof** [comment]
The problem is that if a library I'm depending on creates an ssl context for some reason during load or compile time, my dumped image will be broken.  I noticed this because https://github.com/fukamachi/dexador, for example, seems to do something like this.

I guess a sufficient fix would be to add an exported function or macro that forces reinitialization.

**Comment by mtstickney** [comment]
Right; unfortunately, OpenSSL is stateful and it's state isn't preserved by a dump. cl+ssl's own sense of whether initialization has been done _is_ preserved by a dump.

I don't know of a portable way to do the right thing automatically, but at least in SBCL cl+ssl could add an entry to `sb-ext:*save-hooks*` to unset those variables on dump. Without being able to do something similar in other lisps, it might not be worth it to behave differently on one implementation, though.

Having an exported way to force initialization is a good idea; working with images almost always requires this sort of thing.

**Comment by avodonosov** [comment]
Have you tried to call cl+ssl:reload() after your SBCL image is loaded? 

This is required, cl+ssl:reload is intended to support image reload.

**Comment by avodonosov** [comment]
Closing this, because the test case in the issue description is not using `(cl+ssl:reload)`

**Comment by fiddlerwoaroof** [comment]
This is still broken.

```lisp
% sbcl --no-userinit \
     --load ~/quicklisp/setup.lisp \
     --eval '(ql:quickload :cl+ssl)' \
     --eval '(cl+ssl:make-context)' \
     --eval '(terpri)' \
     <<EOF
(save-lisp-and-die "/tmp/foobar"
                   :executable t
                   :toplevel (lambda () (cl+ssl:reload) (cl+ssl:make-context)))
EOF
```
Then:
```sh
% /tmp/foobar
CORRUPTION WARNING in SBCL pid 15085 pthread 0x101160580:
Memory fault at 0x12400de9c (pc=0x1019cff84)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.

debugger invoked on a SB-SYS:MEMORY-FAULT-ERROR in thread
#<THREAD "main thread" RUNNING {7006190003}>:
  Unhandled memory fault at #x12400DE9C.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

("bogus stack frame")
0]
```

**Comment by avodonosov** [comment]
I tried removing the `(make-context)` from the :toplevel function, just `(reload)` is left, and it still crashes. 

If instead I remove `--eval (make-context)` evaluated before saving - the saved image does not crash.

I don't know what it is,

**Comment by avodonosov** [comment]
The reason is found - `ssl-ctx-free` here: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/e6385587b6839ac8e5c78bf084d58a461f011fee/src/ffi.lisp#L1331

**Comment by avodonosov** [comment]
@deadtrickster , why did you decide to add this: https://github.com/cl-plus-ssl/cl-plus-ssl/commit/0e6bff00db512d55c81b3c4b5f61876854e43a0e

Have you encountered any problem in absence of ssl-ctx-free here?
I am thinking to remove this - it is more likely to expect the lisp image saving does not preserve foreign memory, so the the foreign object is not valid to be freed after the image is restored.

**Comment by mtstickney** [comment]
If `cl+ssl:reload` doesn't free any existing context object, then that context will be leaked when `reload` is called. It does the right thing in a dumped image, where there is initially no context to leak, but it makes it unsafe to call any other time.

It does fix this problem, and a small memory leak isn't the worst thing that could happen (probably people won't call `cl+ssl:reload` much), but it seems the sort of thing people might not notice until well after they've written buggy `reload`-calling code.

I think always calling `cl+ssl:reload` as part of the dump process does the right thing, albeit maybe accidentally: any existing context is freed and discarded, and the global vars are unset so when the image is loaded things will be initialized without attempting to clean up anything. `reload` doesn't actually initialize anything itself, so it works adequately as a de-init function too. Maybe that should be formalized as a requirement for dumping images, possibly with a better name? It's the least ridiculous thing I can come up with at the moment.

**Comment by avodonosov** [comment]
@mtstickney , interesting idea to have a pre image dump function. 

But at the moment cl+ssl:reload is documented as a required function to be called after image is loaded. Changing that will break backward compatibility. 

As for memory leak of any reload -calling code that is not part of image reloading - such usage would be against the api docs - the only purpose of reload is to be called after image is reloaded.

Not also, the current `reload` is not 100% suitable for de-init function, because it calls `cffi:use-foreign-library`.
