### ISSUE TITLE
SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by osktyn** [cl-plus-ssl/cl-plus-ssl#73]
Hi. I'm restarting an internal server that's been down for some time. We use self-signed certificates, but now (due some upgrade the last year perhaps?) I'm getting the error:

`SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN`

Is there a way to tell CL+SSL that self-signed certs are ok to use? The only reference to this error I find in the code is the place where it signals as an error. I don't think we have changed anything else in our certificate structure.

Latest quicklisp and cl+ssl. Openssl 1.1.1b.

**Comment by avodonosov** [comment]
Set `cl+ssl:*make-ssl-client-stream-verify-default*` to nil to switch to the old behavour.

Since ~ 2017-07-03 `cl+ssl:make-ssl-client-stream` by default verifies the server certificate. Docs: https://common-lisp.net/project/cl-plus-ssl/
