### ISSUE TITLE
Order of operations in install-key-and-cert?

### ISSUE THREAD

**Issue by jlahd** [cl-plus-ssl/cl-plus-ssl#74]
This is a bit odd. I was installing a certain web service on a brand new Ubuntu 18.04 AWS instance. libSSL version seems to be 1.1.
When I tried to connect to the server via HTTPS, the server just threw a `SSL initialization error: Can't load RSA private key file /.../whatever.key` into my face.
Investigating, I found out that the error from libssl was `error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch`. A quick googling said this error is raised when the private key and certificate do not match. Well, they could not possibly match, as the private key is loaded _first_ and the certificate only _after that_ in `install-key-and-cert` in `streams.lisp`.
I switched the order of the `ssl-use-rsa-privatekey-file` and `ssl-use-certificate-file` operations in the function and lo, everything started working.
What is odd is that I have successfully - for years - used the (unmodified) CL+SSL on another server (running Ubuntu 14.04 and libSSL 1.0.0). Has something changed in libSSL? What is the correct order of the operations (any potential bad things from switching the order as I did)?
Any insights?

**Comment by avodonosov** [comment]
I personally not familiar with this enough to comment; but thanks for sharing.

**Comment by informatimago** [comment]
Indeed, the certificate must be installed first, because openssl validates the private key public modulus with the one present in the certificate.  Exchange the two forms in that function to have the when certificate form before the when key:

```
(defun install-key-and-cert (handle key certificate)
  (when certificate
    (unless (eql 1 (ssl-use-certificate-file handle
                                             certificate
                                             +ssl-filetype-pem+))
      (error 'ssl-error-initialize
             :reason (format nil "Can't load certificate ~A" certificate))))
  (when key
    (unless (eql 1 (ssl-use-rsa-privatekey-file handle
                                                key
                                                +ssl-filetype-pem+))
      (error 'ssl-error-initialize :reason (format nil "Can't load RSA private key file ~A" key)))))
```
