### ISSUE TITLE
simple error about improper keyword

### ISSUE THREAD

**Issue by vr3dc** [cl-plus-ssl/cl-plus-ssl#82]
Hi,

I am a little inexperienced to offer a fix but when using ccl and dexador to grab a webpage, I get the following error.
(defvar *url* "https://lispcookbook.github.io/cl-cookbook/")
(defvar *request* (dex:get *url*))

Incorrect keyword arguments in (:HOSTNAME
                                "lispcookbook.github.io"
                                :VERIFY
                                T
                                :CERTIFICATE
                                NIL
                                :KEY
                                NIL
                                :PASSWORD
                                NIL) .

There is no :verify keyword in (CL+SSL:MAKE-SSL-CLIENT-STREAM NIL :CERTIFICATE NIL :KEY NIL :PASSWORD NIL :METHOD NIL :EXTERNAL-FORMAT NIL :CLOSE-CALLBACK NIL :UNWRAP-STREAM-P NIL :CIPHER-LIST NIL :HOSTNAME NIL)

I am not even sure how this function ends up on top of the stack when it's lambda list is different than the error. 

Thanks for your time and consideration.

**Comment by avodonosov** [comment]
https://github.com/cl-plus-ssl/cl-plus-ssl/blob/109c67fd8bceaea33b79f4531caf4c55ed240c5d/src/streams.lisp#L384

The function had the :verify argument as you can see.

You somehow loading a very old version of cl+ssl, which doesn't match the dexador expectations.

How do you load the libraries? Do you use quicklisp?

**Comment by avodonosov** [comment]
What does (asdf:system-source-directory "cl+ssl") return? 

This should show where the .asd file of cl+ssl you loaded is located.

**Comment by vr3dc** [comment]
Hello Anton,
Thanks for your reply. Sorry I didn't see it yesterday. Yes, I do use quicklisp to load your library.
Here is the return value you asked to see: 

(asdf:system-source-directory "cl+ssl")
#P"/usr/share/common-lisp/source/cl+ssl/"
I was expecting it to come from my "~/quicklisp/dists/quicklisp/software/cl+ssl-20190521". I guess I need to purge that location and then let it repopulate.

Thanks again,Pat ODonnell

(format nil "~(~36r@~36r.~36r~)" 53332176 57596424 16438) 

    On Wednesday, June 19, 2019, 1:02:53 AM EDT, Anton Vodonosov <notifications@github.com> wrote:  
 
 
What does (asdf:system-source-directory "cl+ssl") return?

This should show where the .asd file of cl+ssl you loaded is located.

**Comment by vr3dc** [comment]
Anton,
You were correct about it being an old configuration. I had to repopulate the /usr/share.... location manually but it sprang to life. Thanks for pointing the way.
Pat

(format nil "~(~36r@~36r.~36r~)" 53332176 57596424 16438) 

    On Thursday, June 20, 2019, 9:25:28 AM EDT, patrick ODonnell <vr3dc@yahoo.com> wrote:  
 
 Hello Anton,
Thanks for your reply. Sorry I didn't see it yesterday. Yes, I do use quicklisp to load your library.
Here is the return value you asked to see: 

(asdf:system-source-directory "cl+ssl")
#P"/usr/share/common-lisp/source/cl+ssl/"
I was expecting it to come from my "~/quicklisp/dists/quicklisp/software/cl+ssl-20190521". I guess I need to purge that location and then let it repopulate.

Thanks again,Pat ODonnell

(format nil "~(~36r@~36r.~36r~)" 53332176 57596424 16438) 

    On Wednesday, June 19, 2019, 1:02:53 AM EDT, Anton Vodonosov <notifications@github.com> wrote:  
 
 
What does (asdf:system-source-directory "cl+ssl") return?

This should show where the .asd file of cl+ssl you loaded is located.

**Comment by avodonosov** [comment]
@vr3dc, most likely, the files in /usr/share/common-lisp/source/cl+ssl/ are result of installing cl+ssl with your OS package manager. For example as described here: https://www.cliki.net/common-lisp-controller. If so, just remove the OS package and use Quicklisp only.
