### ISSUE TITLE
How should MAKE-CONTEXT be used for an SSL-Server?

### ISSUE THREAD

**Issue by phmarek** [cl-plus-ssl/cl-plus-ssl#86]
Comments say that `SSL-CHECK-VERIFY-P` et al are deprecated.

There's `MAKE-CONTEXT`, right -- but how should that be used with a server like `HUNCHENTOOT`? Should it be something like `(SETF *ssl-global-context* (make-context ...))` before even loading HT?

How would one process then run two SSL sockets with different options? (Eg. different CAs, different client certs, etc.)?

**Comment by phmarek** [comment]
also see https://gist.github.com/phmarek/d0ae810936b4f246fec8e2609d60604b

**Comment by hineios** [comment]
After spending most of yesterday's reading documentation on Open SSL, and the API CL+SSL, I am also with some doubts regarding the use of `SSL_CTX`.

As I understand it, please do correct me if I am wrong, the `SSL_CTX` is used to keep common settings used in the creation of sockets to avoid having to repeat them accross the creation of several sockets.
Currently, I am under the impression that, if you only use one `SSL_CTX` in your program, you do not need to specify it, as it will be used per default (I am probably wrong regarding this).

So, I would create a `SSL_CTX` using `cl+ssl:make-context` and just create sockets as needed and they will use this context by default, am I correct?

Or do I need to always use the macro `cl+ssl:with-global-context` even when using only one context?

**Comment by avodonosov** [comment]
I think servers like hunchentoot should introduce their own variable for ssl context (in case of hunchentoot this could be an acceptor slot).  Then hunchentoot then should wrap all calls to `cl+ssl:make-ssl-server-stream` into `cl+ssl:with-global-context`. There is no way to use a context local to hunchentoot instance without adjusting hunchentoot code.

In the future it may be good for cl+ssl to introduce a `context` parameter to all methods like `cl+ssl:make-ssl-server-stream`, so caller can simply pass his context as a parameter without wrapping the call into a macro.

In the case of libraries like drakma, the user code can control the ssl context withotu changing drakma code, by wraping `drakma:http-request` calls into `cl+ssl:with-global-context`.

**Comment by avodonosov** [comment]
Actually, one could use even the current hunchentoot. Derive your acceptor class form hunchentoot:ssl-acceptor, and override or introduce an :around method for `hunchentoot:initialize-connection-stream`. In this method do something like
```common-lisp
    (cl+ssl:with-global-context ((ssl-context my-ssl-acceptor))
       (call-next-method))
```

For your understanding, here is the current code of hunchentoot:initialize-connection-stream method for hunchentoot:ssl-acceptor:

```common-lisp
#-:lispworks
(defmethod initialize-connection-stream ((acceptor ssl-acceptor) stream)
  ;; attach SSL to the stream if necessary
  (call-next-method acceptor
                    (cl+ssl:make-ssl-server-stream stream
                                                   :certificate (acceptor-ssl-certificate-file acceptor)
                                                   :key (acceptor-ssl-privatekey-file acceptor)
                                                   :password (acceptor-ssl-privatekey-password acceptor))))
```

**Comment by avodonosov** [comment]
I think in scope of this issue it will be good to add this information to the doc.

**Comment by hineios** [comment]
So basically, for the time being, we always have to wrap our calls to `ssl+cl:make-ssl-server-stream` with the macro `ssl+cl:with-global-context`.
Hum... 🤔 

However, when creating contexts with CL+SSL we do not provide the certificates.
Imagine I want to set the default certificate for connections created while using a certain context:

```
(let ((my-context (cl+ssl:make-context)))
           ;; Firstl I setup the global context's certificate
	   (cl+ssl:with-global-context (my-context)
	     (cl+ssl:use-certificate-chain-file "/path/to/my/cert.pem"))

           ;; Then when I create a SSL Stream, that certificate is used
	   (cl+ssl:with-global-context (my-context)
	     (cl+ssl:make-ssl-server-stream my-usocket)))
```

Is this in way correct?
Or must I always specify the the `:certificate` argument to `cg+ssl:make-ssl-server-stream`?

**Comment by avodonosov** [comment]
> So basically, for the time being, we always have to wrap our calls to ssl+cl:make-ssl-server-stream with the macro ssl+cl:with-global-context.
Hum... thinking

Yes. cl+ssl can be enhanced to introduce a context parameter in all calls, but currently, we don't have that. The quickest way to allow a user to provide a context was to introduce the macro and that's what was done.

> However, when creating contexts with CL+SSL we do not provide the certificates.

I think you can use  `ssl-ctx-use-certificate-chain-file` to set the certificate to your context:

```common-lisp
(defparameter *my-context*
  (let ((ctx (cl+ssl:make-context ...)))
    (cl+ssl:ssl-ctx-use-certificate-chain-file ctx ...)
    ctx))
```
and then use `*my-context*` everywhere.

> Or must I always specify the the :certificate argument to cg+ssl:make-ssl-server-stream?
If you the call to cl+ssl:make-ssl-server-stream is the code you control, then it's file approach too, I think.
