### ISSUE TITLE
darwin ABCL library issues

### ISSUE THREAD

**Issue by slyrus** [cl-plus-ssl/cl-plus-ssl#88]
On ABCL, I get:

```
CL-USER> (format nil "~X" (cl+ssl::ssl-eay))
"20000000"
```
Whereas on SBCL, I get:
```
CL-USER> (format nil "~X" (cl+ssl::ssl-eay))
"1000214F"
```
It seems that I'm getting the wrong libraries ssl-eay function. If I modify ffi.lisp as follows:

```
modified   src/ffi.lisp
@@ -125,7 +125,7 @@ (defmacro define-crypto-function-ex ((&key since vanished) name-and-options &bod
               *cl+ssl-crypto-foreign-function-names*
               :test 'equal)
      (defcfun-versioned (:since ,since :vanished ,vanished)
-         ,(append name-and-options  #+(and lispworks darwin) '(:library libcrypto))
+         ,(append name-and-options  #+(and (or abcl lispworks) darwin) '(:library libcrypto))
        ,@body)))
 
 (defmacro define-crypto-function (name-and-options &body body)
```

I get the correct answer. I'm not sure if this is the right fix, but it fixes my problem. Thoughts on the best way to address this?

**Comment by avodonosov** [comment]
The current lispworks case is here because on darwin lispworks itself loads boringssl, and when we then load openssl and deeclare ffi functions without explicitly specifying the :library option, some foreign symbols are resolved as boringssl symbols, others (which are absent in boringssl I think) are resolved as openssl functions.

We could remove the reader conditional an just always pass the :library option, but I'm afraid the :cl+ssl-foreign-libs-already-loaded feature flag may not work if the :library option is specified.

What problem do you have except the unexpected value returned from the (cl+ssl::ssl-eay) ?

**Comment by avodonosov** [comment]
In the ffi.lisp file we have the following function:

```common-lisp

(defun libresslp ()
  ;; LibreSSL can be distinguished by
  ;; OpenSSL_version_num() always returning 0x020000000,
  ;; where 2 is the major version number.
  ;; http://man.openbsd.org/OPENSSL_VERSION_NUMBER.3
  ;; And OpenSSL will never use the major version 2:
  ;; "This document outlines the design of OpenSSL 3.0, the next version of OpenSSL after 1.1.1"
  ;; https://www.openssl.org/docs/OpenSSL300Design.html
  (= #x20000000 (compat-openssl-version)))

```

And in several places the code is conditionalized based this function.

**Comment by avodonosov** [comment]
Unlike lispworks, on abcl you seem to have libressl loaded, not boringssl - boringssl returns different version number, 0x1010007f. 
https://boringssl.googlesource.com/boringssl/+/refs/heads/master/include/openssl/base.h#176

**Comment by slyrus** [comment]
Yeah, I have no idea how libressl gets loaded. As you suggest, it may be by Java. I will confess to not really knowing what's going on here. The original problem I was trying to solve can be found here [https://abcl.org/trac/ticket/464](https://abcl.org/trac/ticket/464). Using '(:library libcrypto) at least fixes that. The underlying failure is that my process thinks that (openssl-is-at-least 1 1) should return t, and then it attempts to call tls-method which fails. I'm certainly open to other/better solutions, but the current situation doesn't work for me. Thanks!

**Comment by avodonosov** [comment]
Where exactly in cl+ssl code the version check work badly?

As you can see in

https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/src/ffi.lisp, we have (libresslp)

**Comment by slyrus** [comment]
I'm not sure what your asking here. Yes, there is a check for libresslp. But default-ssl-method doesn't check for libresslp and tries to call tls-method, and fails. Putting in the obvious check causes yet another failure, so I'm not sure if just checking for libresslp in default-ssl-method is the right fix.

**Comment by avodonosov** [comment]
Nevermind, I forgot your situation results from a mix of libressl with openssl.

What prevents me from just merging this is I don't know how it will affect the :cl+ssl-foreign-libs-already-loaded feature flag. 

If not that, we could just use :library libcrypto unconditionally for all lisps and OSes.

**Comment by avodonosov** [comment]
I realized that worrying about :cl+ssl-foreign-libs-already-loaded when abcl doesn't work at all doesn't make sense.

So I'll commit this fix with a proper comment, later, by the end of this week.

**Comment by avodonosov** [comment]
Merged the PR
