### ISSUE TITLE
decode-certificate-from-file needs to use a "buffer". 

### ISSUE THREAD

**Issue by Yehouda** [cl-plus-ssl/cl-plus-ssl#95]
decode-certificate uses cffi:with-pointer-to-vector-data on its BYTES argument, so
it must be created by cffi:make-shareable-byte-vector. See cffi doc in 
https://github.com/cffi/cffi/blob/master/doc/shareable-vectors.txt

decode-certificate-from-file calls decode-certificate with BYTES which it 
creates, so it must create it by cffi:make-shareable-byte-vector,  which it can do
by using make-buffer (which calls cffi:make-shareable-byte-vector). Suggested 
changes below. Note that I don't have my branch, I just load from quicklisp, 
which is why I don't do a pull request.

At least on LispWorks, it currently gets an error in tests  VERIFY-GOOGLE-CERT-DNS-WILDCARD,
VERIFY-GOOGLE-CERT-PRINTABLE-STRING,  VERIFY-GOOGLE-CERT-BMP-STRING, VERIFY-GOOGLE-CERT ,
VERIFY-GOOGLE-CERT-WITHOUT-DNS,  VERIFY-GOOGLE-CERT-TELETEX-STRING and VERIFY-GOOGLE-CERT-UNIVERSAL-STRING,
and the changes below fix these.

The other usages of with-pointer-to-vector-data in cl+sll look to me ok. 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; new functions slurp-stream-into-buffer and read-file-into-buffer.,
;;; which return a buffer that is creted by 
;;; (maybe useful elsehwere). 

(defun slurp-stream-into-buffer (stream)
  (let ((seq (make-buffer (file-length stream))))
    (read-sequence seq stream)
    seq))

(defun read-file-into-buffer (path)
  (with-open-file (stream path :element-type '(unsigned-byte 8))
    (slurp-stream-into-buffer stream)))

;;;; decode-certificate-from-file change to use read-file-into-buffer

(defun decode-certificate-from-file (path &key format)
  (let ((bytes   (read-file-into-buffer path))
        (format (or format (cert-format-from-path path))))
    (decode-certificate format bytes)))

**Comment by avodonosov** [comment]
Values created with make-buffer are not guaranteed to work when passed to read-sequence.
Better to use cffi:make-shareable-byte-vector directly.

**Comment by avodonosov** [comment]
@Yehouda adjusted your proposal to simply use ffi:make-shareable-byte-vector in slurp-stream, see the last commit. Please test on LispWorks.

**Comment by Yehouda** [comment]
Ok by me. 

I don't actually get the code directly from git, I load it using quicklisp.

I copied x509.lisp from here on top of my version and ran the tests on lispworks, they work ok. 

Really test it properly only after the next quicklisp release.
